SELECT BEL.BELID, BEL.AKTID, BEL.BELCODE, BEL.RSID, BEL.KNOTENID, BEL.RSTYP, BEL.PAID, BEL.FAID, BEL.BEGINNRELATIV, BEL.BEGINN, BEL.ENDE, BEL.DAUER, BEL.TEXT, BEL.BELBESTAETIGT, BEL.POSITION, BEL.VOID, BEL.LANG, BEL.VODID, BEL.DATUM, BEL.ZEIT, BEL.ABGEGLICHEN, BEL.EXTERNCODE
FROM DISDBA.BEL BEL
WHERE (BEL.RSTYP='B') AND (BEL.FAID<>'-1')
ORDER BY BEL.FAID, BEL.BEGINN DESC
