SELECT
  PA.PAID,
  PA.PID,
  FA.FAID,
  FA.FID,
  DISPENS.*

FROM DISDBA.FA FA,
     DISDBA.PA PA,
     (SELECT
       DOKUMENT.FAID,
       ELDAT_CUST_751.VERSION_ID,
       ELDAT_CUST_751.DOKUMENT_ID,
       ELDAT_CUST_751.STRUKTUR_ELEMENT_ID,
       ELDAT_CUST_751.HEBELAST,
       ELDAT_CUST_751.COMBO_VOLLDISPENS,
       ELDAT_CUST_751.COMBO_SPORT,
       ELDAT_CUST_751.COMBO_AGOGIK,
       ELDAT_CUST_751.DISPENS_FREIZEITSPORT,
       ELDAT_CUST_751.AMPEL_DISPENS_SOMATIK,
       ELDAT_CUST_751.DISPENS_BEMERKUNG_SOMATIK,
       ELDAT_CUST_751.COMBO_SPORT_TEILDISPENS,
       ELDAT_CUST_751.COMBO_AGOGIK_TEILDISPENS,
       ELDAT_CUST_751.DB_NAME_KOMPLETT,
       ELDAT_CUST_751.DB_ORGEINHEIT,
       ELDAT_CUST_751.FIRST_VERSION_ID
     FROM DOCDBA.DOKUMENT DOKUMENT,
          DOCDBA.DOKUMENT_VERSION DOKUMENT_VERSION,
          DOCADMIN.ELDAT_CUST_751 ELDAT_CUST_751
     WHERE ELDAT_CUST_751.DOKUMENT_ID = DOKUMENT_VERSION.DOKUMENT_ID
     AND ELDAT_CUST_751.VERSION_ID = DOKUMENT_VERSION.VERSION_ID
     AND DOKUMENT.DOKUMENT_ID = DOKUMENT_VERSION.DOKUMENT_ID
     AND ((ELDAT_CUST_751.STRUKTUR_ELEMENT_ID = 858)
     AND (DOKUMENT_VERSION.IST_AKTUELL = 'T'))

     ORDER BY DOKUMENT.FAID) DISPENS


WHERE PA.PAID = FA.PAID
AND FA.FAID = DISPENS.FAID

ORDER BY PA.PAID