SELECT PA.PID, FA.FID, PA.PAID, FA.FAID,
RTRIM(GetDfByAnbindung(FA.FAID,'Fa','Abkuerzung','Org','Org'))

FROM DISDBA.FA FA, DISDBA.PA PA
WHERE PA.PAID = FA.PAID AND ((PA.PID='10643') AND (FA.FID='1'))
ORDER BY PA.PAID