SELECT
  sr.id as survey_response_id, 
  sr.response, 
  sr.event_id, 
  sr.filled, 
  ev.patient as patient_id,
  first(s.id) as stay_id

   
  ((cast(response AS json))->>'Datum') as datum,
  TO_DATE(((cast(response AS json))->>'Datum'), 'YYYY-MM-DD HH24:MI:SS')  as datum_date,
  SUBSTRING(((cast(response AS json))->>'Datum'),12,5) AS datum_time,
  SUBSTRING(((cast(response AS json))->>'Datum'),1,4)::integer AS datum_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'Datum'), 'YYYY-MM-DD HH24:MI:SS')) AS datum_week,
  ((cast(response AS json))->>'BDI1') as BDI1,
  ((cast(response AS json))->>'BDI2') as BDI2,
  ((cast(response AS json))->>'BDI3') as BDI3,
  ((cast(response AS json))->>'BDI4') as BDI4,
  ((cast(response AS json))->>'BDI5') as BDI5,
  ((cast(response AS json))->>'BDI6') as BDI6,
  ((cast(response AS json))->>'BDI7') as BDI7,
  ((cast(response AS json))->>'BDI8') as BDI8,
  ((cast(response AS json))->>'BDI9') as BDI9,
  ((cast(response AS json))->>'BDI10') as BDI10,
  ((cast(response AS json))->>'BDI11') as BDI11,
  ((cast(response AS json))->>'BDI12') as BDI12,
  ((cast(response AS json))->>'BDI13') as BDI13,
  ((cast(response AS json))->>'BDI14') as BDI14,
  ((cast(response AS json))->>'BDI15') as BDI15,
  ((cast(response AS json))->>'BDI16') as BDI16,
  ((cast(response AS json))->>'BDI17') as BDI17,
  ((cast(response AS json))->>'BDI18') as BDI18,
  ((cast(response AS json))->>'BDI19') as BDI19,
  ((cast(response AS json))->>'BDI20') as BDI20,
  ((cast(response AS json))->>'BDI21') as BDI21,
  ((cast(response AS json))->>'BDI_Score') as BDI_Summe,
  ((cast(response AS json))->>'Erhebungszeitpunkt') as erhebungszeitpunkt,
  ((cast(response AS json))->>'FID') as fid,
  ((cast(response AS json))->>'PID') as pid,
  ((cast(response AS json))->>'andererZeitpunkt') as andererzeitpunkt,
  ((cast(response AS json))->>'datestamp') as datestamp,
  TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')  as datestamp_date,
  SUBSTRING(((cast(response AS json))->>'datestamp'),12,5) AS datestamp_time,
  SUBSTRING(((cast(response AS json))->>'datestamp'),1,4)::integer AS datestamp_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')) AS datestamp_week,
  ((cast(response AS json))->>'id') as id,
  ((cast(response AS json))->>'lastpage') as lastpage,
  ((cast(response AS json))->>'optinomixHASH') as optinomixhash,
  ((cast(response AS json))->>'startdate') as startdate,
  TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')  as startdate_date,
  SUBSTRING(((cast(response AS json))->>'startdate'),12,5) AS startdate_time,
  SUBSTRING(((cast(response AS json))->>'startdate'),1,4)::integer AS startdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')) AS startdate_week,
  ((cast(response AS json))->>'startlanguage') as startlanguage,
  ((cast(response AS json))->>'submitdate') as submitdate,
  TO_DATE(((cast(response AS json))->>'submitdate'), 'YYYY-MM-DD HH24:MI:SS')  as submitdate_date,
  SUBSTRING(((cast(response AS json))->>'submitdate'),12,5) AS submitdate_time,
  SUBSTRING(((cast(response AS json))->>'submitdate'),1,4)::integer AS submitdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'submitdate'), 'YYYY-MM-DD HH24:MI:SS')) AS submitdate_week,

  random_hash,
  scheduled,
  filled,
  module,

FROM survey_responses as sr 
LEFT JOIN event as ev on ev.id = sr.event_id 
LEFT JOIN stay as s on s.patient = ev.patient and s.start <= ev.created_at and (s.stop >= ev.created_at or s.stop is null) 
GROUP BY sr.id, sr.response, sr.event_id, sr.filled, ev.patient