SELECT
  PA.PID id_pid,
  PA.PAID id_paid,
  FA.FID id_fid,
  FA.FAID id_faid,
  CASE FA.FID
    WHEN '1' THEN (PA.PID || '01' || '00')
    WHEN '2' THEN (PA.PID || '02' || '00') 
    WHEN '3' THEN (PA.PID || '03' || '00') 
    WHEN '4' THEN (PA.PID || '04' || '00') 
    WHEN '5' THEN (PA.PID || '05' || '00') 
    WHEN '6' THEN (PA.PID || '06' || '00') 
    WHEN '7' THEN (PA.PID || '07' || '00') 
    WHEN '8' THEN (PA.PID || '08' || '00') 
    WHEN '9' THEN (PA.PID || '09' || '00') 
    ELSE (PA.PID || FA.FID || '00') 
  END CIS_FID,  

  FA.EINTRITT EINTRITT,
  FA.ZEITEINTRITT ZEITEINTRITT,
  FA.AUSTRITT AUSTRITT,
  FA.ZEITAUSTRITT ZEITAUSTRITT,
  RTRIM(GetDfByAnbindung(FA.FAID, 'Fa', 'Abkuerzung', 'Org', 'Org')) ORG_CURRENT,

  CASE GetDisStationAtDate(TRUNC(CURRENT_DATE), FA.FAID)
    WHEN 'A2' THEN 'EAS' 
    WHEN 'A3' THEN 'EAS' 
    WHEN 'C0' THEN 'EAS' 
    WHEN 'B0' THEN 'EP' 
    WHEN 'B1' THEN 'EP' 
    WHEN 'B2' THEN 'EP' 
    WHEN 'C1' THEN 'EP' 
    WHEN 'C2' THEN 'EP' 
    WHEN 'D0' THEN 'EP' 
    WHEN 'D1' THEN 'EP' 
    WHEN 'TK' THEN 'TK' 
    ELSE '?' 
  END ORG,  


  CASE 
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'regul% Austritt' THEN 1
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'Abbruch Patient%' THEN 2
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'Abbruch Klinik' THEN 3
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'Uebertritt in andere Klinik' THEN 4
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'Uebertritt innerhalb des S%dhangs' THEN 5
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'auf Initiative Dritter' THEN 6
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'Tod (nicht Suizid)' THEN 7
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'Suizid w%hrend der Behandlungsdauer' THEN 8
    WHEN BELEGUNG.STATISTIK_KANTON_AUSTRITTSART LIKE 'anderer Grund' THEN 9
    ELSE 90 
  END AUSTRITT_TYP,


  CASE 
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Patient gestorben' THEN 1
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'somatische Klinik' THEN 2
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'psychiatrische Klinik station%r' THEN 3
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'psychiatrische Klinik teilstation%r' THEN 4
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'teilstation%re Nachbetreuung' THEN 4
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'andere Klinik / Rehab.-zentrum' THEN 5
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Strafvollzugsanstalt' THEN 6
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'andere station%re Behandlung' THEN 7
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'S%dhang station%r' THEN 8
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Fachstelle fur Alkoholprobleme' THEN 9
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Therapeutische WG' THEN 10
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Sozialdienst' THEN 11
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Sozialdienst / Fachstelle' THEN 11
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Vormund / Beistand' THEN 12
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'PsychiaterIn' THEN 13
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Hausarzt / Haus%rztin' THEN 14
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Psychologe / Psychologin' THEN 15
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'TherapeutIn der Klinik ambulant' THEN 16
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'andere ambulante Betreuung' THEN 17
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'keine Nachbetreuung n%tig' THEN 18
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Angeh%rige' THEN 19
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'keine Nachbetreuung, obwohl n%tig' THEN 20
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Pflegepersonal, Spitex' THEN 21
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'Tagesklinik Sudhang' THEN 22
    WHEN BELEGUNG.STATISTIK_KANTON_WEITERBEH LIKE 'sonstige' THEN 23
    ELSE 90 
  END WEITERBEHANDLUNG_TYP,


  CASE
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '00 gestorben' THEN 00
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '11 Zuhause, alleine' THEN 11
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '12 Zuhause, mit anderen' THEN 12
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE 'alte Wohnung / Wohnort' THEN 12
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '20 Krankenheim, Pflegeheim' THEN 20
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '31 Wohnheim' THEN 31
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '32 Altersheim, andere sozialmed. Instit.' THEN 32
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '40 Psychiatrische Klinik' THEN 40
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '50 Rehabilitationsklinik' THEN 50
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '60 anderes Krankenhaus (Akutspital)' THEN 60
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '70 Strafvollzugsanstalt' THEN 70
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '81 ohne festen Wohnsitz' THEN 81
    WHEN BELEGUNG.STATISTIK_KANTON_WOHNSITUATION LIKE '82 andere' THEN 82
    ELSE 90 
  END WOHNSITUATION_TYP,  

  CASE BELEGUNG.STATISTIK_KANTON_NEUEADRESSE
    WHEN 'Neue Adresse oder Telefonnummer' THEN 1
    ELSE 0 
  END ADRESSE_TYP,  

  BELEGUNG.*

FROM 
  DISDBA.FA FA,
  DISDBA.PA PA,
  (SELECT
     DocDBA.Dokument.FAID,
     DocADMIN.ELDAT_CUST_1151.*
   FROM
     DocAdmin.ELDAT_CUST_1151, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_1151.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_1151.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_1151.Struktur_Element_Id = 1115 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_1151.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
  ) BELEGUNG

WHERE 
   ((PA.PAID = FA.PAID) AND (FA.FAID = BELEGUNG.FAID)) AND
   FA.FID is not null



