SELECT
 NULL,
  :dteLeft                     AS "dteLeft",
  :dteRight                    AS "dteRight",        
  SEId_Essensort.EO            AS "Essensort",
   RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Nummer', 'Ga', 'Ga1')) AS "F#10001822#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Nummer', 'Ga', 'Ga2')) AS "F#10001867#",
  Pa.PaId AS "F#570#",
  Pa.AHV AS "F#488#",
  DECODE(Pa.Abgeglichen,'T','X','') AS "F#2140#",
  Pa.Adresse1 AS "F#486#",
  Pa.Adresse2 AS "F#487#",
  Pa.Kanton AS "F#2145#",
  Pa.Land AS "F#2146#",
  Pa.Ort AS "F#546#",
  Pa.PLZ AS "F#545#",
  Pa.PLZ || ' ' || Pa.Ort AS "F#527#",
  DECODE(Pa.Geburtsdatum, TO_DATE('30.12.1899', 'dd.mm.yyyy'), '', TRUNC(TO_NUMBER(MONTHS_BETWEEN(SYSDATE, Pa.Geburtsdatum)/12))) AS "F#3096#",
  DECODE(Pa.Geschlecht, 1, 'Herr', 2, 'Frau') AS "F#489#",
  RTRIM(GetDfByPF(Pa.PaId,-1, 'Code', 'Bmpa1', 'BmPa1')) AS "F#490#",
  GetPaColorByPaFA(Pa.PaId,-1,'BmPa1', 'BmPa1') AS "F#531#",
  RTRIM(GetDfByPF(Pa.PaId,-1,       'Abkuerzung', 'Bmpa1', 'BmPa1')) AS "F#600#",
  RTRIM(GetDfByPF(Pa.PaId,-1, 'Txt', 'Bmpa1', 'BmPa1')) AS "F#491#",
  RTRIM(GetDfByPF(Pa.PaId,-1, 'ZusatzText', 'Bmpa1', 'BmPa1')) AS "F#492#",
  RTRIM(GetDfByPF(Pa.PaId,-1, 'Code', 'Bmpa2', 'BmPa2')) AS "F#493#",
  GetPaColorByPaFA(Pa.PaId,-1,'BmPa2', 'BmPa2') AS "F#532#",
  RTRIM(GetDfByPF(Pa.PaId,-1,       'Abkuerzung', 'Bmpa2', 'BmPa2')) AS "F#601#",
  RTRIM(GetDfByPF(Pa.PaId,-1, 'Txt', 'Bmpa2', 'BmPa2')) AS "F#494#",
  RTRIM(GetDfByPF(Pa.PaId,-1, 'ZusatzText', 'Bmpa2', 'BmPa2')) AS "F#495#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'BmPa3', 'BmPa3')) AS "F#830#",
  GetPaColorByPaFA(Pa.PaId, -1, 'BmPa3', 'BmPa3') AS "F#834#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Abkuerzung', 'BmPa3', 'BmPa3')) AS "F#833#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'BmPa3', 'BmPa3')) AS "F#831#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'BmPa4', 'BmPa4')) AS "F#840#",
  GetPaColorByPaFA(Pa.PaId, -1, 'BmPa4', 'BmPa4') AS "F#844#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Abkuerzung', 'BmPa4', 'BmPa4')) AS "F#843#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'BmPa4', 'BmPa4')) AS "F#841#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'BmPa5', 'BmPa5')) AS "F#850#",
  GetPaColorByPaFA(Pa.PaId, -1, 'BmPa5', 'BmPa5') AS "F#854#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Abkuerzung', 'BmPa5', 'BmPa5')) AS "F#853#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'BmPa5', 'BmPa5')) AS "F#851#",
  Pa.Beruf AS "F#2151#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'Pc', 'Pc')) AS "F#496#",
  GetPaColorByPaFA(Pa.PaId,-1,'Pc', 'Pc') AS "F#533#",
  RTRIM(GetDfByPF(Pa.PaId, -1,      'Abkuerzung', 'Pc', 'Pc')) AS "F#602#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'Pc', 'Pc')) AS "F#497#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'Pc', 'Pc')) AS "F#498#",
  Pa.Heimatort AS "F#2149#",
  Pa.eMail AS "F#2147#",
  Pa.Erstellt_Kuerzel AS "F#2142#",
  Pa.Erstellt_Datum AS "F#2141#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Abkuerzung', 'PaFi', 'PaFi')) AS "F#2154#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'PaFi', 'PaFi')) AS "F#2152#",
  GetPaColorByPaFA(Pa.PaId,-1,'PaFi', 'PaFi') AS "F#550#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'PaFi', 'PaFi')) AS "F#2153#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'PaFi', 'PaFi')) AS "F#2155#",
  Pa.Text AS "F#499#",
  Pa.GeburtsDatum AS "F#500#",
  Pa.Geburtsname AS "F#2148#",
  DECODE(Pa.Geschlecht, 1, 'm', 2, 'f') AS "F#501#",
  Pa.Geschlecht AS "F#4827#",
  DECODE(Pa.Geschlecht, 1, 'm', 2, 'w') AS "F#3986#",
  NVL(Pa.Geschuetzt,'F') AS "F#6449#",
  Pa.Paid AS "F#5901#",
  TO_CHAR(pa.geburtsdatum, 'yyyy') AS "F#549#",
  Pa.Kanton AS "F#2865#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Abkuerzung', 'Rg', 'Rg')) AS "F#1194#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'Rg', 'Rg')) AS "F#1192#",
  GetPaColorByPaFA(Pa.PaId,-1,'Rg', 'Rg') AS "F#551#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'Rg', 'Rg')) AS "F#1193#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'Rg', 'Rg')) AS "F#2157#",
  GetDfByPF(Pa.PaId, -1, 'Adresse1'                 , 'Adr', 'Kntk2') AS "F#4580#",
  GetDfByPF(Pa.PaId, -1, 'Adresse2'                 , 'Adr', 'Kntk2') AS "F#4581#",
  GetDfByPF(Pa.PaId, -1, 'Anrede'                   , 'Adr', 'Kntk2') AS "F#4582#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Code',     'BmAdA','BmAdA','Kntk2') AS "F#1140#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk2', 'BmAdA', 'BmAdA', 'Code'                 )) AS "F#10000064#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Farbe',    'BmAdA','BmAdA','Kntk2') AS "F#1144#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk2', 'BmAdA', 'BmAdA', 'Farbe'     , 'FIRST')) AS "F#10000066#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Abkuerzung','BmAdA','BmAdA','Kntk2') AS "F#1143#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk2', 'BmAdA', 'BmAdA', 'Abkuerzung'           )) AS "F#10000068#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk2', 'BmAdA', 'BmAdA', 'Txt'                  )) AS "F#10000070#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Txt',      'BmAdA','BmAdA','Kntk2') AS "F#1141#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk2', 'BmAdA', 'BmAdA', 'ZusatzText'           )) AS "F#10000072#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Code',     'BmAdB','BmAdB','Kntk2') AS "F#1150#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Farbe',    'BmAdB','BmAdB','Kntk2') AS "F#1154#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Abkuerzung','BmAdB','BmAdB','Kntk2') AS "F#1153#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Txt',      'BmAdB','BmAdB','Kntk2') AS "F#1151#",
  GetDfByPF(Pa.PaId, -1, 'Bezeichnung'              , 'Adr', 'Kntk2') AS "F#4583#",
  GetDfByPF(Pa.PaId, -1, 'Code'                     , 'Adr', 'Kntk2') AS "F#810#",
  GetDfByPF(Pa.PaId, -1, 'eMail'                    , 'Adr', 'Kntk2') AS "F#4584#",
  GetPaColorByPaFA(Pa.PaId, -1, 'Adr', 'Kntk2') AS "F#814#",
  GetDfByPF(Pa.PaId, -1, 'Fax'                      , 'Adr', 'Kntk2') AS "F#4585#",
  GetDfByPF(Pa.PaId, -1, 'Abkuerzung'               , 'Adr', 'Kntk2') AS "F#813#",
  GetDfByPF(Pa.PaId, -1, 'Land'                     , 'Adr', 'Kntk2') AS "F#4586#",
  GetDfByPF(Pa.PaId, -1, 'Name'                     , 'Adr', 'Kntk2') AS "F#4587#",
  GetDfByPF(Pa.PaId, -1, 'Ort'                      , 'Adr', 'Kntk2') AS "F#4588#",
  GetDfByPF(Pa.PaId, -1, 'Plz'                      , 'Adr', 'Kntk2') AS "F#4589#",
  GetDfByPF(Pa.PaId, -1, 'Reihenfolge'              , 'Adr', 'Kntk2') AS "F#4590#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Code'              , 'Adr', 'Kntk2') AS "F#10000052#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Abkuerzung'        , 'Adr', 'Kntk2') AS "F#10000054#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Txt'               , 'Adr', 'Kntk2') AS "F#10000056#",
  GetDfByPF(Pa.PaId, -1, 'Telefon1'                 , 'Adr', 'Kntk2') AS "F#4591#",
  GetDfByPF(Pa.PaId, -1, 'Telefon2'                 , 'Adr', 'Kntk2') AS "F#4592#",
  GetDfByPF(Pa.PaId, -1, 'Txt'                      , 'Adr', 'Kntk2') AS "F#811#",
  Pa.TxtKntk2 AS "F#1181#",
  GetDfByPF(Pa.PaId, -1, 'Titel'                    , 'Adr', 'Kntk2') AS "F#4593#",
  GetDfByPF(Pa.PaId, -1, 'Vorname'                  , 'Adr', 'Kntk2') AS "F#4594#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz1'       , 'Adr', 'Kntk2') AS "F#10000058#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz2'       , 'Adr', 'Kntk2') AS "F#10000060#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz3'       , 'Adr', 'Kntk2') AS "F#10000062#",
  GetDfByPF(Pa.PaId, -1, 'ZusatzText'               , 'Adr', 'Kntk2') AS "F#812#",
  GetDfByPF(Pa.PaId, -1, 'Adresse1'                 , 'Adr', 'Kntk3') AS "F#4620#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Adresse2', 'Adr', 'Kntk3')) AS "F#4621#",
  GetDfByPF(Pa.PaId, -1, 'Adresse2'                 , 'Adr', 'Kntk3') AS "F#4604#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Anrede', 'Adr', 'Kntk3')) AS "F#4622#",
  GetDfByPF(Pa.PaId, -1, 'Anrede'                   , 'Adr', 'Kntk3') AS "F#4605#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk3', 'BmAdA', 'BmAdA', 'Code'                 )) AS "F#10000113#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Code',     'BmAdA','BmAdA','Kntk3') AS "F#1160#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Farbe',    'BmAdA','BmAdA','Kntk3') AS "F#1164#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk3', 'BmAdA', 'BmAdA', 'Farbe'     , 'FIRST')) AS "F#10000115#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Abkuerzung','BmAdA','BmAdA','Kntk3') AS "F#1163#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk3', 'BmAdA', 'BmAdA', 'Abkuerzung'           )) AS "F#10000117#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk3', 'BmAdA', 'BmAdA', 'Txt'                  )) AS "F#10000119#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Txt',      'BmAdA','BmAdA','Kntk3') AS "F#1161#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntk3', 'BmAdA', 'BmAdA', 'ZusatzText'           )) AS "F#10000121#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Code',     'BmAdB','BmAdB','Kntk3') AS "F#1170#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Farbe',    'BmAdB','BmAdB','Kntk3') AS "F#1174#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Abkuerzung','BmAdB','BmAdB','Kntk3') AS "F#1173#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Txt',      'BmAdB','BmAdB','Kntk3') AS "F#1171#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Bezeichnung', 'Adr', 'Kntk3')) AS "F#4623#",
  GetDfByPF(Pa.PaId, -1, 'Bezeichnung'              , 'Adr', 'Kntk3') AS "F#4606#",
  GetDfByPF(Pa.PaId, -1, 'Code'                     , 'Adr', 'Kntk3') AS "F#820#",
  GetDfByPF(Pa.PaId, -1, 'eMail'                    , 'Adr', 'Kntk3') AS "F#4618#",
  GetPaColorByPaFA(Pa.PaId, -1, 'Adr', 'Kntk3') AS "F#824#",
  GetDfByPF(Pa.PaId, -1, 'Fax'                      , 'Adr', 'Kntk3') AS "F#4608#",
  GetDfByPF(Pa.PaId, -1, 'Abkuerzung'               , 'Adr', 'Kntk3') AS "F#823#",
  GetDfByPF(Pa.PaId, -1, 'Land'                     , 'Adr', 'Kntk3') AS "F#1073#",
  GetDfByPF(Pa.PaId, -1, 'Name'                     , 'Adr', 'Kntk3') AS "F#4609#",
  GetDfByPF(Pa.PaId, -1, 'Ort'                      , 'Adr', 'Kntk3') AS "F#4610#",
  GetDfByPF(Pa.PaId, -1, 'Plz'                      , 'Adr', 'Kntk3') AS "F#4611#",
  GetDfByPF(Pa.PaId, -1, 'Reihenfolge'              , 'Adr', 'Kntk3') AS "F#4612#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Code'              , 'Adr', 'Kntk3') AS "F#10000095#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Abkuerzung'        , 'Adr', 'Kntk3') AS "F#10000097#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Txt'               , 'Adr', 'Kntk3') AS "F#10000099#",
  GetDfByPF(Pa.PaId, -1, 'Telefon1'                 , 'Adr', 'Kntk3') AS "F#4613#",
  GetDfByPF(Pa.PaId, -1, 'Telefon2'                 , 'Adr', 'Kntk3') AS "F#4614#",
  GetDfByPF(Pa.PaId, -1, 'Txt'                      , 'Adr', 'Kntk3') AS "F#821#",
  Pa.TxtKntk3 AS "F#1182#",
  GetDfByPF(Pa.PaId, -1, 'Titel'                    , 'Adr', 'Kntk3') AS "F#4615#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Titel', 'Adr', 'Kntk3')) AS "F#4633#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Vorname', 'Adr', 'Kntk3')) AS "F#4634#",
  GetDfByPF(Pa.PaId, -1, 'Vorname'                  , 'Adr', 'Kntk3') AS "F#1071#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz1'       , 'Adr', 'Kntk3') AS "F#10000106#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz2'       , 'Adr', 'Kntk3') AS "F#10000108#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz3'       , 'Adr', 'Kntk3') AS "F#10000110#",
  GetDfByPF(Pa.PaId, -1, 'ZusatzText'               , 'Adr', 'Kntk3') AS "F#822#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'eMail', 'Adr', 'Kntk3')) AS "F#4624#",
  GetDfByPF(Pa.PaId, -1, 'Adresse1'                 , 'Adr', 'Kntkt') AS "F#504#",
  GetDfByPF(Pa.PaId, -1, 'Adresse2'                 , 'Adr', 'Kntkt') AS "F#505#",
  GetDfByPF(Pa.PaId, -1, 'Anrede'                   , 'Adr', 'Kntkt') AS "F#506#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Code',     'BmAdA','BmAdA','Kntkt') AS "F#1120#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntkt', 'BmAdA', 'BmAdA', 'Code'                 )) AS "F#10000187#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntkt', 'BmAdA', 'BmAdA', 'Farbe'     , 'FIRST')) AS "F#10000189#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Farbe',    'BmAdA','BmAdA','Kntkt') AS "F#1124#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntkt', 'BmAdA', 'BmAdA', 'Abkuerzung'           )) AS "F#10000191#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Abkuerzung','BmAdA','BmAdA','Kntkt') AS "F#1123#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntkt', 'BmAdA', 'BmAdA', 'Txt'                  )) AS "F#10000193#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Txt',      'BmAdA','BmAdA','Kntkt') AS "F#1121#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'Kntkt', 'BmAdA', 'BmAdA', 'ZusatzText'           )) AS "F#10000195#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Code',     'BmAdB','BmAdB','Kntkt') AS "F#1130#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Farbe',    'BmAdB','BmAdB','Kntkt') AS "F#1134#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Abkuerzung','BmAdB','BmAdB','Kntkt') AS "F#1133#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'Txt',      'BmAdB','BmAdB','Kntkt') AS "F#1131#",
  GetDfByPF(Pa.PaId, -1, 'Bezeichnung'              , 'Adr', 'Kntkt') AS "F#507#",
  GetDfByPF(Pa.PaId, -1, 'Code'                     , 'Adr', 'Kntkt') AS "F#502#",
  GetDfByPF(Pa.PaId, -1, 'eMail'                    , 'Adr', 'Kntkt') AS "F#508#",
  GetPaColorByPaFA(Pa.PaId, -1, 'Adr', 'Kntkt') AS "F#4638#",
  GetDfByPF(Pa.PaId, -1, 'Fax'                      , 'Adr', 'Kntkt') AS "F#509#",
  GetDfByPF(Pa.PaId, -1, 'Abkuerzung'               , 'Adr', 'Kntkt') AS "F#510#",
  GetDfByPF(Pa.PaId, -1, 'Land'                     , 'Adr', 'Kntkt') AS "F#511#",
  GetDfByPF(Pa.PaId, -1, 'Name'                     , 'Adr', 'Kntkt') AS "F#512#",
  GetDfByPF(Pa.PaId, -1, 'Ort'                      , 'Adr', 'Kntkt') AS "F#513#",
  GetDfByPF(Pa.PaId, -1, 'Plz'                      , 'Adr', 'Kntkt') AS "F#514#",
  GetDfByPF(Pa.PaId, -1, 'Reihenfolge'              , 'Adr', 'Kntkt') AS "F#515#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Code'              , 'Adr', 'Kntkt') AS "F#10000157#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Abkuerzung'        , 'Adr', 'Kntkt') AS "F#10000159#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Txt'               , 'Adr', 'Kntkt') AS "F#10000161#",
  GetDfByPF(Pa.PaId, -1, 'Telefon1'                 , 'Adr', 'Kntkt') AS "F#516#",
  GetDfByPF(Pa.PaId, -1, 'Telefon2'                 , 'Adr', 'Kntkt') AS "F#517#",
  Pa.TxtKntkt AS "F#1180#",
  GetDfByPF(Pa.PaId, -1, 'Txt'                      , 'Adr', 'Kntkt') AS "F#503#",
  GetDfByPF(Pa.PaId, -1, 'Titel'                    , 'Adr', 'Kntkt') AS "F#518#",
  GetDfByPF(Pa.PaId, -1, 'Vorname'                  , 'Adr', 'Kntkt') AS "F#519#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz1'       , 'Adr', 'Kntkt') AS "F#10000173#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz2'       , 'Adr', 'Kntkt') AS "F#10000175#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz3'       , 'Adr', 'Kntkt') AS "F#10000177#",
  GetDfByPF(Pa.PaId, -1, 'ZusatzText'               , 'Adr', 'Kntkt') AS "F#520#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Abkuerzung', 'Spr', 'Spr')) AS "F#2069#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Code', 'Spr', 'Spr')) AS "F#2067#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'Txt', 'Spr', 'Spr')) AS "F#2068#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'Spr', 'Spr')) AS "F#2156#",
  Pa.Land AS "F#3095#",
  Pa.Mobile AS "F#868#",
  Pa.Mutiert_Kuerzel AS "F#2144#",
  Pa.Mutiert_Datum AS "F#2143#",
  Pa.Name AS "F#521#",
  Pa.Name || ' ' || Pa.Vorname AS "F#547#",
  Pa.Name || ' ' || Pa.Vorname || DECODE(NVL(Pa.Geburtsdatum, TO_DATE('30.12.1899', 'dd.mm.yyyy')), TO_DATE('30.12.1899', 'dd.mm.yyyy'), '', ' ' || Pa.Geburtsdatum) AS "F#2050#",
  Pa.Name || ' ' || Pa.Vorname || DECODE(NVL(Pa.Geburtsdatum, TO_DATE('30.12.1899', 'dd.mm.yyyy')), TO_DATE('30.12.1899', 'dd.mm.yyyy'), '', ' ' || TO_CHAR(Pa.Geburtsdatum, 'yyyy')) AS "F#523#",
  Pa.Name || ' ' || Pa.Vorname ||', ' || Pa.Ort AS "F#548#",
  Pa.Name || ' ' || Pa.Vorname || DECODE(NVL(LENGTH(Pa.PID), 0), 0, '', ' (PID ' || Pa.PID || ')') AS "F#524#",
  Pa.Nationalitaet AS "F#2150#",
  Pa.Ort AS "F#2054#",
  Pa.PID AS "F#526#",
  Pa.Plz AS "F#2053#",
  Pa.Plz || ' ' || Pa.Ort AS "F#2055#",
  Pa.Plz || ' ' || Pa.Ort || ', ' || Pa.Adresse1 AS "F#2066#",
  GetDfByPF(Pa.PaId, -1, 'Adresse1'                 , 'Adr', 'CR_Psych') AS "F#10002051#",
  GetDfByPF(Pa.PaId, -1, 'Adresse2'                 , 'Adr', 'CR_Psych') AS "F#10002050#",
  GetDfByPF(Pa.PaId, -1, 'Anrede'                   , 'Adr', 'CR_Psych') AS "F#10002117#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'CR_Psych', 'BmAdA', 'BmAdA', 'Code'                 )) AS "F#10002090#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'CR_Psych', 'BmAdA', 'BmAdA', 'Farbe'     , 'FIRST')) AS "F#10002024#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'CR_Psych', 'BmAdA', 'BmAdA', 'Abkuerzung'           )) AS "F#10002059#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'CR_Psych', 'BmAdA', 'BmAdA', 'Txt'                  )) AS "F#10002068#",
  RTRIM(GetDfOfDfItemByAnbindung(Pa.PaId, 'Pa', 'Adr', 'CR_Psych', 'BmAdA', 'BmAdA', 'ZusatzText'           )) AS "F#10002081#",
  GetDfByPF(Pa.PaId, -1, 'Bezeichnung'              , 'Adr', 'CR_Psych') AS "F#10002020#",
  GetDfByPF(Pa.PaId, -1, 'Code'                     , 'Adr', 'CR_Psych') AS "F#10002082#",
  GetDfByPF(Pa.PaId, -1, 'eMail'                    , 'Adr', 'CR_Psych') AS "F#10002094#",
  GetPaColorByPaFA(Pa.PaId, -1, 'Adr', 'CR_Psych') AS "F#10002085#",
  GetDfByPF(Pa.PaId, -1, 'Fax'                      , 'Adr', 'CR_Psych') AS "F#10002097#",
  GetDfByPF(Pa.PaId, -1, 'Abkuerzung'               , 'Adr', 'CR_Psych') AS "F#10002108#",
  GetDfByPF(Pa.PaId, -1, 'Land'                     , 'Adr', 'CR_Psych') AS "F#10002036#",
  GetDfByPF(Pa.PaId, -1, 'Name'                     , 'Adr', 'CR_Psych') AS "F#10002100#",
  GetDfByPF(Pa.PaId, -1, 'Ort'                      , 'Adr', 'CR_Psych') AS "F#10002053#",
  GetDfByPF(Pa.PaId, -1, 'Plz'                      , 'Adr', 'CR_Psych') AS "F#10002019#",
  GetDfByPF(Pa.PaId, -1, 'Reihenfolge'              , 'Adr', 'CR_Psych') AS "F#10002112#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Code'              , 'Adr', 'CR_Psych') AS "F#10002042#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Abkuerzung'        , 'Adr', 'CR_Psych') AS "F#10002028#",
  GetDfByPF(Pa.PaId, -1, 'Df_Spr_Txt'               , 'Adr', 'CR_Psych') AS "F#10002061#",
  GetDfByPF(Pa.PaId, -1, 'Telefon1'                 , 'Adr', 'CR_Psych') AS "F#10002021#",
  GetDfByPF(Pa.PaId, -1, 'Telefon2'                 , 'Adr', 'CR_Psych') AS "F#10002073#",
  GetDfByPF(Pa.PaId, -1, 'Txt'                      , 'Adr', 'CR_Psych') AS "F#10002080#",
  GetDfByPF(Pa.PaId, -1, 'Titel'                    , 'Adr', 'CR_Psych') AS "F#10002026#",
  GetDfByPF(Pa.PaId, -1, 'Vorname'                  , 'Adr', 'CR_Psych') AS "F#10002043#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz1'       , 'Adr', 'CR_Psych') AS "F#10002052#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz2'       , 'Adr', 'CR_Psych') AS "F#10002040#",
  GetDfByAnbindung(Pa.PaId, 'Pa', 'Zusatz3'       , 'Adr', 'CR_Psych') AS "F#10002087#",
  GetDfByPF(Pa.PaId, -1, 'ZusatzText'               , 'Adr', 'CR_Psych') AS "F#10002071#",
  Pa.SozVersNr AS "F#5925#",
  Pa.Sprache AS "F#2070#",
  GetPaColorByPaFA(Pa.PaId,-1,'Spr', 'Spr') AS "F#552#",
  Pa.Telefon2 AS "F#528#",
  Pa.Telefon1 AS "F#529#",
  Pa.Telefon1 || DECODE(NVL(LENGTH(Pa.Telefon1), 0), 0, '', ' ') || Pa.Telefon2 || ' ' || Pa.Mobile AS "F#2065#",
  Pa.Titel AS "F#2137#",
  Pa.Vorname AS "F#530#",
  Pa.Zivilstand AS "F#2138#",
  DECODE(Pa.Zivilstand,'0', 'unbekannt', '1', 'ledig', '2', 'verheiratet', '3', 'getrennt', '4', 'geschieden', '5', 'verwitwet', 6, 'eingetragene Partnerschaft', 7, 'aufgel. eingetragene Partnerschaft', '') AS "F#2139#",
   DECODE(Fa.Abgeglichen,'T','X','') AS "F#2077#",
  Fa.AdminAbschlussdatum AS "F#2863#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1'            , 'Adr', 'ArbGe') AS "F#2120#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2'            , 'Adr', 'ArbGe') AS "F#2121#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa',   'Anrede', 'Adr', 'ArbGe')), 1, 'Herrn',  2, 'Frau', 3, 'An die Eltern von', '') AS "F#10000046#",
  CASE WHEN INSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Adr', 'ArbGe')              , ',') > 0 THEN NULL ELSE DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Adr', 'ArbGe')),               1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') END AS "F#10000048#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede'              , 'Adr', 'ArbGe') AS "F#2122#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdA', 'BmAdA', 'Code'                 )) AS "F#10001478#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdA', 'BmAdA', 'Farbe'     , 'FIRST')) AS "F#10001480#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdA', 'BmAdA', 'Abkuerzung'           )) AS "F#10001482#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdA', 'BmAdA', 'Txt'                  )) AS "F#10001484#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdA', 'BmAdA', 'ZusatzText'           )) AS "F#10001486#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdB', 'BmAdB', 'Code'                 )) AS "F#10001488#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdB', 'BmAdB', 'Farbe'     , 'FIRST')) AS "F#10001490#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdB', 'BmAdB', 'Abkuerzung'           )) AS "F#10001492#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdB', 'BmAdB', 'Txt'                  )) AS "F#10001494#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'ArbGe', 'BmAdB', 'BmAdB', 'ZusatzText'           )) AS "F#10001496#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung'         , 'Adr', 'ArbGe') AS "F#2123#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'                , 'Adr', 'ArbGe') AS "F#10000005#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail'               , 'Adr', 'ArbGe') AS "F#2124#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'EAN'    , 'Adr', 'ArbGe') AS "F#4664#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Adr', 'ArbGe') AS "F#10000039#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax'                 , 'Adr', 'ArbGe') AS "F#2125#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung'          , 'Adr', 'ArbGe') AS "F#2126#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land'                , 'Adr', 'ArbGe') AS "F#2127#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name'                , 'Adr', 'ArbGe') AS "F#2128#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort'                 , 'Adr', 'ArbGe') AS "F#2129#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Badge'          , 'Adr', 'ArbGe') AS "F#10000041#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Kurzel'          , 'Adr', 'ArbGe') AS "F#10000042#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Pager'          , 'Adr', 'ArbGe') AS "F#10000043#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Tel_Intern'          , 'Adr', 'ArbGe') AS "F#10000044#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz'                 , 'Adr', 'ArbGe') AS "F#2130#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge'         , 'Adr', 'ArbGe') AS "F#2131#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Code'         , 'Adr', 'ArbGe') AS "F#10000014#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Abkuerzung'   , 'Adr', 'ArbGe') AS "F#10000016#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Txt'          , 'Adr', 'ArbGe') AS "F#10000018#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1'            , 'Adr', 'ArbGe') AS "F#2132#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2'            , 'Adr', 'ArbGe') AS "F#2133#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'                 , 'Adr', 'ArbGe') AS "F#10000022#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel'               , 'Adr', 'ArbGe') AS "F#2134#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname'             , 'Adr', 'ArbGe') AS "F#2135#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz1'         , 'Adr', 'ArbGe') AS "F#10000026#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz2'         , 'Adr', 'ArbGe') AS "F#10000028#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz3'         , 'Adr', 'ArbGe') AS "F#10000030#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText'          , 'Adr', 'ArbGe') AS "F#2136#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Aa', 'Aa') AS "F#535#",
  Fa.Austritt-Fa.Eintritt+1 AS "F#2075#",
  DECODE(Fa.AufAbruf,'T','X','') AS "F#2091#",
  Fa.DatumAufgebot AS "F#2090#",
  DECODE(Fa.AufgebotSchriftlich,'T','X','') AS "F#2093#",
  DECODE(Fa.AufgebotTelefonisch,'T','X','') AS "F#2092#",
  Fa.VisumAufgebot                     AS "F#866#",
  To_Char(Fa.ZeitAufgebot,'HH24:MI') AS "F#865#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Aa', 'Aa')) AS "F#351#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Aa', 'Aa')) AS "F#604#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Aa', 'Aa')) AS "F#352#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Aa', 'Aa')) AS "F#353#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1'            , 'Adr', 'AuftrGeb') AS "F#4952#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2'            , 'Adr', 'AuftrGeb') AS "F#4953#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede'              , 'Adr', 'AuftrGeb') AS "F#4954#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung'         , 'Adr', 'AuftrGeb') AS "F#4955#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'                , 'Adr', 'AuftrGeb') AS "F#4950#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax'                 , 'Adr', 'AuftrGeb') AS "F#4957#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung'          , 'Adr', 'AuftrGeb') AS "F#4958#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land'                , 'Adr', 'AuftrGeb') AS "F#4959#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name'                , 'Adr', 'AuftrGeb') AS "F#4960#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort'                 , 'Adr', 'AuftrGeb') AS "F#4961#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz'                 , 'Adr', 'AuftrGeb') AS "F#4962#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge'         , 'Adr', 'AuftrGeb') AS "F#4963#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Code'         , 'Adr', 'AuftrGeb') AS "F#4964#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Abkuerzung'   , 'Adr', 'AuftrGeb') AS "F#4965#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Txt'          , 'Adr', 'AuftrGeb') AS "F#4966#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1'            , 'Adr', 'AuftrGeb') AS "F#4967#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2'            , 'Adr', 'AuftrGeb') AS "F#4968#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'                 , 'Adr', 'AuftrGeb') AS "F#4951#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel'               , 'Adr', 'AuftrGeb') AS "F#4969#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname'             , 'Adr', 'AuftrGeb') AS "F#4970#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz1'         , 'Adr', 'AuftrGeb') AS "F#4972#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz2'         , 'Adr', 'AuftrGeb') AS "F#4973#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz3'         , 'Adr', 'AuftrGeb') AS "F#4974#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText'          , 'Adr', 'AuftrGeb') AS "F#4971#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail'               , 'Adr', 'AuftrGeb') AS "F#4956#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'      , 'Zl', 'Zl')) AS "F#560#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Zl', 'Zl') AS "F#567#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Zl', 'Zl')) AS "F#612#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'       , 'Zl', 'Zl')) AS "F#561#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Zl', 'Zl')) AS "F#562#",
  DECODE(Fa.AustrittBest,'T','X','') AS "F#2078#",
  Fa.Austritt AS "F#350#",
  To_Char(Fa.Austritt,'dd.mm.yy') AS "F#6331#",
  To_Char(Fa.Austritt,'dd.mm.yyyy') AS "F#995#",
  TO_CHAR(Fa.Austritt,'dd.mm.yyyy') || ' ' || TO_CHAR(Fa.ZeitAustritt,'HH24:MI') AS "F#2062#",
  To_Char(Fa.ZeitAustritt,'HH24:MI') AS "F#556#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Code'      , 'Am', 'Am', 'K', 0) AS "F#3120#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Code'      , 'Am', 'Am', 'K', 1) AS "F#3123#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Abkuerzung', 'Am', 'Am', 'K', 1) AS "F#3124#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Txt'       , 'Am', 'Am', 'K', 1) AS "F#3125#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Code'      , 'Am', 'Am', 'K', 2) AS "F#3126#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Abkuerzung', 'Am', 'Am', 'K', 2) AS "F#3127#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Txt'       , 'Am', 'Am', 'K', 2) AS "F#3128#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Abkuerzung', 'Am', 'Am', 'K', 0) AS "F#3121#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Txt'       , 'Am', 'Am', 'K', 0) AS "F#3122#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Code'      , 'Am', 'Am', 'V', 1) AS "F#3129#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Abkuerzung', 'Am', 'Am', 'V', 1) AS "F#3130#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Txt'       , 'Am', 'Am', 'V', 1) AS "F#3131#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Code'      , 'Am', 'Am', 'V', 2) AS "F#3132#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Abkuerzung', 'Am', 'Am', 'V', 2) AS "F#3133#",
  GetDfByAnbindung_Tree(Fa.FaId, 'Fa', 'Txt'       , 'Am', 'Am', 'V', 2) AS "F#3134#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Am', 'Am')) AS "F#640#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Am', 'Am') AS "F#644#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Am', 'Am')) AS "F#643#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Am', 'Am')) AS "F#641#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Am', 'Am')) AS "F#642#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Agr', 'Agr')) AS "F#630#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Agr', 'Agr') AS "F#634#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Agr', 'Agr')) AS "F#633#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Agr', 'Agr')) AS "F#631#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Agr', 'Agr')) AS "F#632#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1',         'Az', 'BAz', 1) AS "F#4024#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2',         'Az', 'BAz', 1) AS "F#4025#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede',           'Az', 'BAz', 1) AS "F#4026#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung',      'Az', 'BAz', 1) AS "F#4027#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code',             'Az', 'BAz', 1) AS "F#4022#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr',               'Az', 'BAz', 1) AS "F#4028#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail',            'Az', 'BAz', 1) AS "F#4029#",
  GetDfByAnbindung(Fa.FaId,'Fa','EAN','Az','BAz', 1) AS "F#4648#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax',              'Az', 'BAz', 1) AS "F#4030#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion',         'Az', 'BAz', 1) AS "F#4031#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton',           'Az', 'BAz', 1) AS "F#4032#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz',        'Az', 'BAz', 1) AS "F#4033#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung',       'Az', 'BAz', 1) AS "F#4034#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'BAz', 1) AS "F#5160#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name',             'Az', 'BAz', 1) AS "F#4035#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'BAz', 1) || DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 1), '', '', ' ' || SUBSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 1), 1, 1) || '.') ||DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 1), '', '', '(' || GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 1) || ')') AS "F#4047#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort',              'Az', 'BAz', 1) AS "F#4036#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz',              'Az', 'BAz', 1) AS "F#4037#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge',      'Az', 'BAz', 1) AS "F#4038#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName',       'Az', 'BAz', 1) AS "F#4045#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'BAz', 1) AS "F#4044#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1',         'Az', 'BAz', 1) AS "F#4039#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2',         'Az', 'BAz', 1) AS "F#4040#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt',              'Az', 'BAz', 1) AS "F#4023#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',            'Az', 'BAz', 1) AS "F#4041#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',          'Az', 'BAz', 1) AS "F#4042#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','BAz', 1) AS "F#4765#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','BAz', 1) AS "F#4772#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','BAz', 1) AS "F#4779#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText',       'Az', 'BAz', 1) AS "F#4043#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1',         'Az', 'BAz', 2) AS "F#4074#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2',         'Az', 'BAz', 2) AS "F#4075#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede',           'Az', 'BAz', 2) AS "F#4076#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung',      'Az', 'BAz', 2) AS "F#4077#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code',             'Az', 'BAz', 2) AS "F#4072#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr',               'Az', 'BAz', 2) AS "F#4078#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail',            'Az', 'BAz', 2) AS "F#4079#",
  GetDfByAnbindung(Fa.FaId,'Fa','EAN','Az','BAz', 2) AS "F#4649#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax',              'Az', 'BAz', 2) AS "F#4080#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion',         'Az', 'BAz', 2) AS "F#4081#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton',           'Az', 'BAz', 2) AS "F#4082#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz',        'Az', 'BAz', 2) AS "F#4083#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung',       'Az', 'BAz', 2) AS "F#4084#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'BAz', 2) AS "F#5161#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name',             'Az', 'BAz', 2) AS "F#4085#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'BAz', 2) || DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 2), '', '', ' ' || SUBSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 2), 1, 1) || '.') ||DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 2), '', '', '(' || GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 2) || ')') AS "F#4097#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort',              'Az', 'BAz', 2) AS "F#4086#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz',              'Az', 'BAz', 2) AS "F#4087#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge',      'Az', 'BAz', 2) AS "F#4088#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName',       'Az', 'BAz', 2) AS "F#4095#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'BAz', 2) AS "F#4094#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1',         'Az', 'BAz', 2) AS "F#4089#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2',         'Az', 'BAz', 2) AS "F#4090#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt',              'Az', 'BAz', 2) AS "F#4073#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',            'Az', 'BAz', 2) AS "F#4091#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',          'Az', 'BAz', 2) AS "F#4092#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','BAz', 2) AS "F#4766#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','BAz', 2) AS "F#4773#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','BAz', 2) AS "F#4780#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText',       'Az', 'BAz', 2) AS "F#4093#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1',         'Az', 'BAz', 3) AS "F#4124#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2',         'Az', 'BAz', 3) AS "F#4125#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede',           'Az', 'BAz', 3) AS "F#4126#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung',      'Az', 'BAz', 3) AS "F#4127#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code',             'Az', 'BAz', 3) AS "F#4122#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr',               'Az', 'BAz', 3) AS "F#4128#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail',            'Az', 'BAz', 3) AS "F#4129#",
  GetDfByAnbindung(Fa.FaId,'Fa','EAN','Az','BAz', 3) AS "F#4650#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax',              'Az', 'BAz', 3) AS "F#4130#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion',         'Az', 'BAz', 3) AS "F#4131#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton',           'Az', 'BAz', 3) AS "F#4132#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz',        'Az', 'BAz', 3) AS "F#4133#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung',       'Az', 'BAz', 3) AS "F#4134#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'BAz', 3) AS "F#5162#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name',             'Az', 'BAz', 3) AS "F#4135#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'BAz', 3) || DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 3), '', '', ' ' || SUBSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 3), 1, 1) || '.') ||DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 3), '', '', '(' || GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 3) || ')') AS "F#4147#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort',              'Az', 'BAz', 3) AS "F#4136#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz',              'Az', 'BAz', 3) AS "F#4137#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge',      'Az', 'BAz', 3) AS "F#4138#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName',       'Az', 'BAz', 3) AS "F#4145#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'BAz', 3) AS "F#4144#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1',         'Az', 'BAz', 3) AS "F#4139#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2',         'Az', 'BAz', 3) AS "F#4140#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt',              'Az', 'BAz', 3) AS "F#4123#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',            'Az', 'BAz', 3) AS "F#4141#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',          'Az', 'BAz', 3) AS "F#4142#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','BAz', 3) AS "F#4767#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','BAz', 3) AS "F#4774#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','BAz', 3) AS "F#4781#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText',       'Az', 'BAz', 3) AS "F#4143#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1',         'Az', 'BAz', 4) AS "F#4174#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2',         'Az', 'BAz', 4) AS "F#4175#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede',           'Az', 'BAz', 4) AS "F#4176#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung',      'Az', 'BAz', 4) AS "F#4177#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code',             'Az', 'BAz', 4) AS "F#4172#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr',               'Az', 'BAz', 4) AS "F#4178#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail',            'Az', 'BAz', 4) AS "F#4179#",
  GetDfByAnbindung(Fa.FaId,'Fa','EAN','Az','BAz', 4) AS "F#4651#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax',              'Az', 'BAz', 4) AS "F#4180#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion',         'Az', 'BAz', 4) AS "F#4181#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton',           'Az', 'BAz', 4) AS "F#4182#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz',        'Az', 'BAz', 4) AS "F#4183#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung',       'Az', 'BAz', 4) AS "F#4184#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'BAz', 4) AS "F#5163#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name',             'Az', 'BAz', 4) AS "F#4185#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'BAz', 4) || DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 4), '', '', ' ' || SUBSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',  'Az', 'BAz', 4), 1, 1) || '.') ||DECODE(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 4), '', '', '(' || GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',  'Az', 'BAz', 4) || ')') AS "F#4197#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort',              'Az', 'BAz', 4) AS "F#4186#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz',              'Az', 'BAz', 4) AS "F#4187#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge',      'Az', 'BAz', 4) AS "F#4188#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName',       'Az', 'BAz', 4) AS "F#4195#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'BAz', 4) AS "F#4194#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1',         'Az', 'BAz', 4) AS "F#4189#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2',         'Az', 'BAz', 4) AS "F#4190#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt',              'Az', 'BAz', 4) AS "F#4173#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel',            'Az', 'BAz', 4) AS "F#4191#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname',          'Az', 'BAz', 4) AS "F#4192#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','BAz', 4) AS "F#4768#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','BAz', 4) AS "F#4775#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','BAz', 4) AS "F#4782#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText',       'Az', 'BAz', 4) AS "F#4193#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Az', 'BAz')) AS "F#356#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Az', 'BAz')) AS "F#357#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'BAz')), 1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') AS "F#10000508#",
  CASE WHEN INSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'BAz')              , ',') > 0 THEN NULL ELSE DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'BAz')),               1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') END AS "F#10000509#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'BAz')) AS "F#358#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'BAz')), 1, 'r', '') AS "F#10000507#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung', 'Az', 'BAz')) AS "F#359#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Az', 'BAz')) AS "F#354#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr', 'Az', 'BAz')) AS "F#360#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail', 'Az', 'BAz')) AS "F#361#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'EAN', 'Az', 'BAz') AS "F#4647#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax', 'Az', 'BAz')) AS "F#362#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion', 'Az', 'BAz')) AS "F#363#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton', 'Az', 'BAz')) AS "F#364#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz', 'Az', 'BAz')) AS "F#365#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Az', 'BAz')) AS "F#366#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'BAz')) AS "F#5157#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'BAz')) AS "F#367#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort', 'Az', 'BAz')) AS "F#368#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Badge'          , 'Adr', 'BAz') AS "F#10003514#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Geburtsdatum'          , 'Adr', 'BAz') AS "F#10003519#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Kurzel'          , 'Adr', 'BAz') AS "F#10003513#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Pager'          , 'Adr', 'BAz') AS "F#10003511#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Tel_Intern'          , 'Adr', 'BAz') AS "F#10003510#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz', 'Az', 'BAz')) AS "F#369#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge', 'Az', 'BAz')) AS "F#370#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName', 'Az', 'BAz')) AS "F#2058#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'BAz')) AS "F#2057#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1', 'Az', 'BAz')) AS "F#371#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2', 'Az', 'BAz')) AS "F#372#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Az', 'BAz')) AS "F#355#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel', 'Az', 'BAz')) AS "F#373#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname', 'Az', 'BAz')) AS "F#374#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','BAz') AS "F#4764#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','BAz') AS "F#4771#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','BAz') AS "F#4778#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Az', 'BAz')) AS "F#375#",
  GetDfByPF_Berecht(Pa.PaId, Fa.FaId, 'Abkuerzung', 'BmFa1', 'BmFa1') AS "F#6109#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'BmFa1', 'BmFa1')) AS "F#376#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'BmFa1', 'BmFa1') AS "F#536#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'BmFa1', 'BmFa1')) AS "F#605#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'BmFa1', 'BmFa1')) AS "F#377#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'BmFa1', 'BmFa1')) AS "F#378#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'BmFa2', 'BmFa2')) AS "F#379#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'BmFa2', 'BmFa2') AS "F#537#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'BmFa2', 'BmFa2')) AS "F#606#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'BmFa2', 'BmFa2')) AS "F#380#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'BmFa2', 'BmFa2')) AS "F#381#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'BmFa3', 'BmFa3')) AS "F#650#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'BmFa3', 'BmFa3') AS "F#654#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'BmFa3', 'BmFa3')) AS "F#653#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'BmFa3', 'BmFa3')) AS "F#651#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'BmFa3', 'BmFa3')) AS "F#652#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'BmFa4', 'BmFa4')) AS "F#660#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'BmFa4', 'BmFa4') AS "F#664#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'BmFa4', 'BmFa4')) AS "F#663#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'BmFa4', 'BmFa4')) AS "F#661#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'BmFa4', 'BmFa4')) AS "F#662#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'BmFa5', 'BmFa5')) AS "F#670#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'BmFa5', 'BmFa5') AS "F#674#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'BmFa5', 'BmFa5')) AS "F#673#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'BmFa5', 'BmFa5')) AS "F#671#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'BmFa5', 'BmFa5')) AS "F#672#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Bf', 'Bf')) AS "F#382#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Bf', 'Bf') AS "F#538#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Bf', 'Bf')) AS "F#607#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Bf', 'Bf')) AS "F#383#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Bf', 'Bf')) AS "F#384#",
  Fa.Fallbezeichnung AS "F#4943#",
  GetDisBettAtTime(TRUNC(Fa.Austritt), Fa.FaId) AS "F#2478#",
  GetDisBettAtTime(TRUNC(Fa.Austritt), Fa.FaId, 'CODE') AS "F#5214#",
  GetDisBettAtTime(TRUNC(Fa.Eintritt), Fa.FaId) AS "F#2477#",
  GetDisBettAtTime(TRUNC(Fa.Eintritt), Fa.FaId, 'CODE') AS "F#5213#",
  GetDisBettTelefonAtTime(TRUNC(Fa.Austritt), Fa.FaId) AS "F#2480#",
  GetDisBettTelefonAtTime(TRUNC(Fa.Eintritt), Fa.FaId) AS "F#2479#",
  GetDisBettTelefonAtTime(sysdate, Fa.FaId) AS "F#6390#",
  GetDisBettAtTime(SYSDATE, Fa.FaId) AS "F#2502#",
  GetDisBettAtTime(SYSDATE, Fa.FaId, 'CODE') AS "F#5216#",
  GetDisStationAtTime(SYSDATE, Fa.FaId) AS "F#2500#",
  GetDisZimmerAtTime(SYSDATE, Fa.FaId) AS "F#2501#",
  GetDisZimmerAtTime(SYSDATE, Fa.FaId, 'CODE') AS "F#5212#",
  GetDisStationAtDate(TRUNC(Fa.Austritt), Fa.FaId) AS "F#2056#",
  GetDisBettAtTime(Akt.Datum+(Akt.Zeit/(24*60*60)), Fa.FaId, 'CODE') AS "F#5215#",
  GetDisZimmerAtTime(Akt.Datum+(Akt.Zeit/(24*60*60)), Fa.FaId, 'CODE') AS "F#5211#",
  GetDisZimmerAtTime(TRUNC(Fa.Austritt), Fa.FaId) AS "F#2476#",
  GetDisZimmerAtTime(TRUNC(Fa.Austritt), Fa.FaId, 'CODE') AS "F#5210#",
  GetDisZimmerAtTime(TRUNC(Fa.Eintritt), Fa.FaId) AS "F#2475#",
  GetDisZimmerAtTime(TRUNC(Fa.Eintritt), Fa.FaId, 'CODE') AS "F#5209#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Dg', 'Dg')) AS "F#385#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Dg', 'Dg') AS "F#539#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Dg', 'Dg')) AS "F#608#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Dg', 'Dg')) AS "F#386#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Dg', 'Dg')) AS "F#387#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Dg', 'Dg2')) AS "F#790#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Dg', 'Dg2') AS "F#794#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Dg', 'Dg2')) AS "F#793#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Dg', 'Dg2')) AS "F#791#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Dg', 'Dg2')) AS "F#792#",
  GetDfByPF_Berecht(Pa.PaId, Fa.FaId, 'Abkuerzung', 'Dz', 'Dz') AS "F#6110#",
  GetDfByPF_Berecht(Pa.PaId, Fa.FaId, 'Txt', 'Dz', 'Dz') AS "F#6108#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Dz', 'Dz')) AS "F#388#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Dz', 'Dz') AS "F#540#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Dz', 'Dz')) AS "F#609#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Dz', 'Dz')) AS "F#389#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Dz', 'Dz')) AS "F#390#",
  To_Char(Fa.Eintritt,'DD.MM.YYYY') || '-' || To_Char(Fa.Austritt,'DD.MM.YYYY') AS "F#555#",
  To_Char(Fa.Austritt-Fa.Eintritt) AS "F#554#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1'            , 'Adr', 'Eins') AS "F#5002#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2'            , 'Adr', 'Eins') AS "F#5003#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede'              , 'Adr', 'Eins') AS "F#5004#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung'         , 'Adr', 'Eins') AS "F#5005#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'                , 'Adr', 'Eins') AS "F#5000#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax'                 , 'Adr', 'Eins') AS "F#5007#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung'          , 'Adr', 'Eins') AS "F#5008#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land'                , 'Adr', 'Eins') AS "F#5009#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name'                , 'Adr', 'Eins') AS "F#5010#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort'                 , 'Adr', 'Eins') AS "F#5011#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz'                 , 'Adr', 'Eins') AS "F#5012#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge'         , 'Adr', 'Eins') AS "F#5013#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Code'         , 'Adr', 'Eins') AS "F#5014#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Abkuerzung'   , 'Adr', 'Eins') AS "F#5015#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Txt'          , 'Adr', 'Eins') AS "F#5016#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1'            , 'Adr', 'Eins') AS "F#5017#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2'            , 'Adr', 'Eins') AS "F#5018#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'                 , 'Adr', 'Eins') AS "F#5001#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel'               , 'Adr', 'Eins') AS "F#5019#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname'             , 'Adr', 'Eins') AS "F#5020#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz1'         , 'Adr', 'Eins') AS "F#5022#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz2'         , 'Adr', 'Eins') AS "F#5023#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz3'         , 'Adr', 'Eins') AS "F#5024#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText'          , 'Adr', 'Eins') AS "F#5021#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail'               , 'Adr', 'Eins') AS "F#5006#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'      , 'Ea', 'Ea')) AS "F#557#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Ea', 'Ea') AS "F#566#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Ea', 'Ea')) AS "F#613#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'       , 'Ea', 'Ea')) AS "F#558#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Ea', 'Ea')) AS "F#559#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Eh', 'Eh')) AS "F#700#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Eh', 'Eh') AS "F#704#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Eh', 'Eh')) AS "F#703#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Eh', 'Eh')) AS "F#701#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Eh', 'Eh')) AS "F#702#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Es', 'Es')) AS "F#710#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Es', 'Es') AS "F#714#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Es', 'Es')) AS "F#713#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Es', 'Es')) AS "F#711#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Es', 'Es')) AS "F#712#",
  Fa.Eintritt AS "F#391#",
  To_Char(Fa.Eintritt,'dd.mm.yy') AS "F#6330#",
  To_Char(Fa.Eintritt,'dd.mm.yyyy') AS "F#994#",
  TO_CHAR(Fa.Eintritt,'dd.mm.yyyy') || ' ' || TO_CHAR(Fa.ZeitEintritt,'HH24:MI') AS "F#2061#",
  To_Char(Fa.ZeitEintritt,'HH24:MI') AS "F#553#",
  DECODE(Fa.Eintrittsuntersuchung,'T','X','') AS "F#2076#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Eg', 'Eg')) AS "F#414#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Eg', 'Eg') AS "F#541#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Eg', 'Eg')) AS "F#610#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Eg', 'Eg')) AS "F#415#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Eg', 'Eg')) AS "F#416#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Ez', 'Ez')) AS "F#720#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Ez', 'Ez') AS "F#724#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Ez', 'Ez')) AS "F#723#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Ez', 'Ez')) AS "F#721#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Ez', 'Ez')) AS "F#722#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Dg', 'EDg2')) AS "F#800#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Dg', 'EDg2') AS "F#804#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Dg', 'EDg2')) AS "F#803#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Dg', 'EDg2')) AS "F#801#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Dg', 'EDg2')) AS "F#802#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'      , 'Dg', 'EDg')) AS "F#563#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Dg', 'EDg')) AS "F#614#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'       , 'Dg', 'EDg')) AS "F#564#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Dg', 'EDg')) AS "F#565#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Az', 'EAz')) AS "F#394#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Az', 'EAz')) AS "F#395#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'EAz')), 1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') AS "F#10000521#",
  CASE WHEN INSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'EAz')              , ',') > 0 THEN NULL ELSE DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'EAz')),               1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') END AS "F#10000522#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'EAz')) AS "F#396#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'EAz')), 1, 'r', '') AS "F#10000520#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung', 'Az', 'EAz')) AS "F#397#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Az', 'EAz')) AS "F#392#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr', 'Az', 'EAz')) AS "F#398#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail', 'Az', 'EAz')) AS "F#399#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'EAN', 'Az', 'EAz') AS "F#4652#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax', 'Az', 'EAz')) AS "F#400#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion', 'Az', 'EAz')) AS "F#401#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton', 'Az', 'EAz')) AS "F#402#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz', 'Az', 'EAz')) AS "F#403#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Az', 'EAz')) AS "F#404#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'EAz')) AS "F#5158#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'EAz')) AS "F#405#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort', 'Az', 'EAz')) AS "F#406#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Badge'          , 'Adr', 'EAz') AS "F#10003524#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Geburtsdatum'          , 'Adr', 'EAz') AS "F#10003529#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Kurzel'          , 'Adr', 'EAz') AS "F#10003523#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Pager'          , 'Adr', 'EAz') AS "F#10003521#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Tel_Intern'          , 'Adr', 'EAz') AS "F#10003520#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz', 'Az', 'EAz')) AS "F#407#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge', 'Az', 'EAz')) AS "F#408#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName', 'Az', 'EAz')) AS "F#2060#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'EAz')) AS "F#10000518#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1', 'Az', 'EAz')) AS "F#409#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2', 'Az', 'EAz')) AS "F#410#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Az', 'EAz')) AS "F#393#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel', 'Az', 'EAz')) AS "F#411#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname', 'Az', 'EAz')) AS "F#412#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','EAz') AS "F#4769#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','EAz') AS "F#4776#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','EAz') AS "F#4783#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Az', 'EAz')) AS "F#413#",
  Fa.DatumAnmeldung AS "F#2085#",
  DECODE(Fa.Notfall,'T','X','') AS "F#2086#",
  Fa.TxtAnmeldung AS "F#2089#",
  Fa.UnfallDatum AS "F#2088#",
  To_Char(Fa.UnfallZeit,'HH24:MI') AS "F#6468#",
  DECODE(Fa.ArztZeugnis,'T','X','') AS "F#2087#",
  Fa.Erstellt_Kuerzel AS "F#2082#",
  Fa.Erstellt_Datum AS "F#2081#",
  Fa.FID AS "F#417#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Az', 'CR_FAz')) AS "F#10001936#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Az', 'CR_FAz')) AS "F#10001947#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'CR_FAz')), 1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') AS "F#10001981#",
  CASE WHEN INSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'CR_FAz')              , ',') > 0 THEN NULL ELSE DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'CR_FAz')),               1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') END AS "F#10001986#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'CR_FAz')) AS "F#10001988#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'CR_FAz')), 1, 'r', '') AS "F#10001995#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung', 'Az', 'CR_FAz')) AS "F#10002006#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Az', 'CR_FAz')) AS "F#10001930#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr', 'Az', 'CR_FAz')) AS "F#10001929#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail', 'Az', 'CR_FAz')) AS "F#10001980#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'EAN', 'Az', 'CR_FAz') AS "F#10001928#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax', 'Az', 'CR_FAz')) AS "F#10001960#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion', 'Az', 'CR_FAz')) AS "F#10001949#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton', 'Az', 'CR_FAz')) AS "F#10001942#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz', 'Az', 'CR_FAz')) AS "F#10001922#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Az', 'CR_FAz')) AS "F#10001916#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'CR_FAz')) AS "F#10001918#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'CR_FAz')) AS "F#10001926#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort', 'Az', 'CR_FAz')) AS "F#10001955#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Badge'          , 'Adr', 'CR_FAz') AS "F#10003544#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Geburtsdatum'          , 'Adr', 'CR_FAz') AS "F#10003549#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Kurzel'          , 'Adr', 'CR_FAz') AS "F#10003543#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Pager'          , 'Adr', 'CR_FAz') AS "F#10003541#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Tel_Intern'          , 'Adr', 'CR_FAz') AS "F#10003540#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz', 'Az', 'CR_FAz')) AS "F#10001970#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge', 'Az', 'CR_FAz')) AS "F#10001919#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName', 'Az', 'CR_FAz')) AS "F#10001975#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'CR_FAz')) AS "F#10001985#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1', 'Az', 'CR_FAz')) AS "F#10001964#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2', 'Az', 'CR_FAz')) AS "F#10001933#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Az', 'CR_FAz')) AS "F#10001954#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel', 'Az', 'CR_FAz')) AS "F#10001994#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname', 'Az', 'CR_FAz')) AS "F#10001923#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','CR_FAz') AS "F#10001990#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','CR_FAz') AS "F#10001912#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','CR_FAz') AS "F#10001940#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Az', 'CR_FAz')) AS "F#10001968#",
  Fa.Fallbezeichnung AS "F#2864#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Af', 'Af')) AS "F#620#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Af', 'Af') AS "F#624#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Af', 'Af')) AS "F#623#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Af', 'Af')) AS "F#621#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Af', 'Af')) AS "F#622#",
  Fa.FreiText AS "F#418#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'GaZA', 'GaZA')) AS "F#730#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'GaZA', 'GaZA') AS "F#734#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'GaZA', 'GaZA')) AS "F#733#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'GaZA', 'GaZA')) AS "F#731#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'GaZA', 'GaZA')) AS "F#732#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'GaZB', 'GaZB')) AS "F#740#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'GaZB', 'GaZB') AS "F#744#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'GaZB', 'GaZB')) AS "F#743#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'GaZB', 'GaZB')) AS "F#741#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'GaZB', 'GaZB')) AS "F#742#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Ga', 'Ga1') || ' ' || GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Ga', 'Ga1')) AS "F#10001818#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Ga', 'Ga1')) AS "F#421#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Ga', 'Ga1')) AS "F#422#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga1', 'BmGa',  'BmGa' , 'Code'                 )) AS "F#680#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga1', 'BmGa',  'BmGa' , 'Abkuerzung'           )) AS "F#683#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga1', 'BmGa',  'BmGa' , 'Txt'                  )) AS "F#681#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga1', 'BmGa',  'BmGa' , 'ZusatzText'           )) AS "F#682#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung', 'Ga', 'Ga1')) AS "F#423#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Ga', 'Ga1')) AS "F#419#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail', 'Ga', 'Ga1')) AS "F#424#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax', 'Ga', 'Ga1')) AS "F#425#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ga_Garantie', 'Ga', 'Ga1')) AS "F#2072#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton', 'Ga', 'Ga1')) AS "F#5080#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_KOSTENGUTSPR', 'Ga', 'Ga1')) AS "F#2098#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ga_Garantie', 'Ga', 'Ga1')) AS "F#2100#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_TXTKOSTENGUTSPR', 'Ga', 'Ga1')) AS "F#10001861#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kontaktperson', 'Ga', 'Ga1')) AS "F#426#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Ga', 'Ga1')) AS "F#427#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Ga', 'Ga1')) AS "F#5082#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Ga', 'Ga1')) AS "F#428#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Nummer', 'Ga', 'Ga1')) AS "F#10001822#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort', 'Ga', 'Ga1')) AS "F#429#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz', 'Ga', 'Ga1')) AS "F#430#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Referenznummer', 'Ga', 'Ga1')) AS "F#431#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge', 'Ga', 'Ga1')) AS "F#432#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1', 'Ga', 'Ga1')) AS "F#433#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2', 'Ga', 'Ga1')) AS "F#434#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Ga', 'Ga1')) AS "F#420#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_VEKANR', 'Ga', 'Ga1')) AS "F#10001820#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_VERSICHERUNGSNR', 'Ga', 'Ga1')) AS "F#2096#",
  GetDfItemOfAdrByPF(Pa.PaId, -1, 'Txt',        'BmAdA', 'BmAdA', 'Kntkt') AS "F#435#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Ga', 'Ga2') || ' ' || GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Ga', 'Ga2')) AS "F#10001863#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Ga', 'Ga2')) AS "F#438#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Ga', 'Ga2')) AS "F#439#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga2', 'BmGa',  'BmGa' , 'Code'                 )) AS "F#690#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga2', 'BmGa',  'BmGa' , 'Abkuerzung'           )) AS "F#693#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga2', 'BmGa',  'BmGa' , 'Txt'                  )) AS "F#691#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Ga',  'Ga2', 'BmGa',  'BmGa' , 'ZusatzText'           )) AS "F#452#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung', 'Ga', 'Ga2')) AS "F#440#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Ga', 'Ga2')) AS "F#436#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail', 'Ga', 'Ga2')) AS "F#441#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax', 'Ga', 'Ga2')) AS "F#442#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ga_Garantie', 'Ga', 'Ga2')) AS "F#2073#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton', 'Ga', 'Ga2')) AS "F#5081#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_KOSTENGUTSPR', 'Ga', 'Ga2')) AS "F#2099#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ga_Garantie', 'Ga', 'Ga2')) AS "F#2101#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_TXTKOSTENGUTSPR', 'Ga', 'Ga2')) AS "F#10001906#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kontaktperson', 'Ga', 'Ga2')) AS "F#443#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Ga', 'Ga2')) AS "F#444#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Ga', 'Ga2')) AS "F#5083#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Ga', 'Ga2')) AS "F#445#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Nummer', 'Ga', 'Ga2')) AS "F#10001867#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort', 'Ga', 'Ga2')) AS "F#446#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz', 'Ga', 'Ga2')) AS "F#447#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Referenznummer', 'Ga', 'Ga2')) AS "F#448#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge', 'Ga', 'Ga2')) AS "F#449#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1', 'Ga', 'Ga2')) AS "F#450#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2', 'Ga', 'Ga2')) AS "F#451#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Ga', 'Ga2')) AS "F#437#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_VEKANR', 'Ga', 'Ga2')) AS "F#10001865#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'GA_VERSICHERUNGSNR', 'Ga', 'Ga2')) AS "F#2097#",
  Fa.Region AS "F#2095#",
  fa.datkostengutspr ||' '|| fa.garantie || ' / ' || fa.datkostengutspr2 || ' ' || fa.garantie2 AS "F#2074#",
  NVL(Fa.Geschuetzt,'F') AS "F#6450#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Gs', 'Gs')) AS "F#750#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Gs', 'Gs') AS "F#754#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Gs', 'Gs')) AS "F#753#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Gs', 'Gs')) AS "F#751#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Gs', 'Gs')) AS "F#752#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Az', 'HAz')) AS "F#455#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Az', 'HAz')) AS "F#456#",
  GetDfItemOfAdrByPF(Pa.PaId, -1, 'Abkuerzung', 'BmAdA', 'BmAdA', 'Kntk3') AS "F#453#",
  GetDfItemOfAdrByPF(Pa.PaId, -1, 'Code',       'BmAdB', 'BmAdB', 'Kntk3') AS "F#454#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1', 'Az', 'HAz')) AS "F#10000532#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2', 'Az', 'HAz')) AS "F#10000533#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'HAz')), 1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') AS "F#457#",
  CASE WHEN INSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'HAz')              , ',') > 0 THEN NULL ELSE DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az',  'HAz')),               1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') END AS "F#10000542#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'HAz')) AS "F#10000534#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Az', 'HAz')), 1, 'r', '') AS "F#10000540#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung', 'Az', 'HAz')) AS "F#458#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Az', 'HAz')) AS "F#10000530#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Dr', 'Az', 'HAz')) AS "F#459#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail', 'Az', 'HAz')) AS "F#460#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'EAN', 'Az', 'HAz') AS "F#4653#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax', 'Az', 'HAz')) AS "F#461#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Funktion', 'Az', 'HAz')) AS "F#462#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kanton', 'Az', 'HAz')) AS "F#463#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Kantonsaz', 'Az', 'HAz')) AS "F#464#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Az', 'HAz')) AS "F#465#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Land', 'Az', 'HAz')) AS "F#5159#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Name', 'Az', 'HAz')) AS "F#466#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort', 'Az', 'HAz')) AS "F#467#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Badge'          , 'Adr', 'HAz') AS "F#10003534#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Geburtsdatum'          , 'Adr', 'HAz') AS "F#10003539#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Kurzel'          , 'Adr', 'HAz') AS "F#10003533#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Pager'          , 'Adr', 'HAz') AS "F#10003531#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Tel_Intern'          , 'Adr', 'HAz') AS "F#10003530#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz', 'Az', 'HAz')) AS "F#468#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge', 'Az', 'HAz')) AS "F#469#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVName', 'Az', 'HAz')) AS "F#10000538#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'TitelVornameName', 'Az', 'HAz')) AS "F#10000537#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1', 'Az', 'HAz')) AS "F#470#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2', 'Az', 'HAz')) AS "F#471#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Az', 'HAz')) AS "F#10000531#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel', 'Az', 'HAz')) AS "F#472#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname', 'Az', 'HAz')) AS "F#473#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ1','Az','HAz') AS "F#4770#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ2','Az','HAz') AS "F#4777#",
  GetDfByAnbindung(Fa.FaId,'Fa','ZUSATZ3','Az','HAz') AS "F#4784#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Az', 'HAz')) AS "F#474#",
  fa.faid AS "F#5900#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Kg', 'Kg')) AS "F#475#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Kg', 'Kg') AS "F#542#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Kg', 'Kg')) AS "F#476#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Kg', 'Kg')) AS "F#477#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Kg', 'Kg')) AS "F#2080#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Kl', 'Kl')) AS "F#478#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Kl', 'Kl') AS "F#543#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Kl', 'Kl')) AS "F#479#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Kl', 'Kl')) AS "F#480#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Kl', 'Kl')) AS "F#2079#",
  (SELECT SUM(NVL(RgLs.Faktor, 1)*RgLs.Anzahl) FROM RgLs, rg, LsAkt WHERE RgLs.LsAktId = LsAkt.LsAktId and rgLs.VersionId=LastRgVersion(RgLs.RgId) AND LsAkt.Verrechenbar='T' and LsAkt.FaId = Fa.FaId and rg.rgid = rgLs.RgId and rg.VersionId = RgLs.VersionId and nvl(rg.IstKassenabrechnung,'F')<>'T') AS "F#5300#",
  (SELECT SUM(NVL(LsAkt.Faktor, 1)*LsAkt.Anzahl) FROM LsAkt WHERE LsAkt.FaId = Fa.FaId AND LsAkt.Verrechenbar='F') AS "F#4679#",
  (Select sum(nvl(LsAkt.Faktor,1)*LsAkt.Anzahl) from LsAkt where LsAkt.FaId = Fa.FaId) AS "F#4296#",
  (SELECT SUM(NVL(LsAkt.Faktor, 1)*LsAkt.Anzahl) FROM LsAkt WHERE LsAkt.FaId = Fa.FaId AND LsAkt.Verrechenbar='T') AS "F#4678#",
  Fa.Mutiert_Kuerzel AS "F#2084#",
  Fa.Mutiert_Datum AS "F#3964#",
  Fa.Mutiert_Datum AS "F#2083#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmCode')) AS "F#3097#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmTxt')) AS "F#3098#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmCode2')) AS "F#3099#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmTxt2')) AS "F#3100#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmCode3')) AS "F#3101#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmTxt3')) AS "F#3102#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmCode4')) AS "F#3103#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmTxt4')) AS "F#3104#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmCode5')) AS "F#3105#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'BmTxt5')) AS "F#3106#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Bezeichnung')) AS "F#2158#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Datum')) AS "F#2159#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Datum')) || ' ' || RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Bezeichnung')) AS "F#2170#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Dauer')) AS "F#2160#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'DauerAV')) AS "F#2161#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'DauerRV')) AS "F#2162#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'DauerRW')) AS "F#2163#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'DauerSec') AS "F#6132#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'MkCode')) AS "F#5078#",
  RTRIM(GetOpsStringF(Pa.PaId, Fa.FaId, 'MkTxt')) AS "F#5079#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Operateur_Kurz')) AS "F#2164#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Operateur_Suchname')) AS "F#2165#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Operateur_VName') AS "F#6135#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Operateur_VornameName') AS "F#6134#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaeAz_Kurz') AS "F#6111#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaeAz_Suchname') AS "F#6112#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaeAz_VName') AS "F#6114#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaeAz_VornameName') AS "F#6113#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaePers_Kurz') AS "F#6115#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaePers_Suchname') AS "F#6116#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaePers_VName') AS "F#6118#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'AnaePers_VornameName') AS "F#6117#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Assistent_Kurz') AS "F#6119#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Assistent_Suchname') AS "F#6120#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Assistent_VName') AS "F#6122#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Assistent_VornameName') AS "F#6121#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Inst_Kurz') AS "F#6123#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Inst_Suchname') AS "F#6124#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Inst_VName') AS "F#6126#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Inst_VornameName') AS "F#6125#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Zudienung_Kurz') AS "F#6127#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Zudienung_Suchname') AS "F#6128#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Zudienung_VName') AS "F#6130#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'Zudienung_VornameName') AS "F#6129#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Text')) AS "F#2166#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Text2')) AS "F#2167#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Text3')) AS "F#2168#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'VonBis') AS "F#6131#",
  RTrim(GetOpsStringF(Pa.PaId, Fa.FaId, 'Zeit')) AS "F#2487#",
  GetOpsStringF(Pa.PaId, Fa.FaId, 'ZeitSec') AS "F#6133#",
  RTrim(GetOpsStringF(Fa.PaId, Fa.FaId, 'LinkedTaBez')) AS "F#2579#",
  RTrim(GetOpsStringF(Fa.PaId, Fa.FaId, 'LinkedTaCode')) AS "F#2580#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Org', 'Org') AS "F#544#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Org', 'Org')) AS "F#481#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Org', 'Org')) AS "F#611#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Org', 'Org')) AS "F#482#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Org', 'Org')) AS "F#483#",
  Pa.PID || ', ' || Fa.FID AS "F#2071#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Pt', 'Pt')) AS "F#760#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Pt', 'Pt') AS "F#764#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Pt', 'Pt')) AS "F#763#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Pt', 'Pt')) AS "F#761#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Pt', 'Pt')) AS "F#762#",
  Fa.TxtPlanung AS "F#867#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse1'            , 'Adr', 'Sonst') AS "F#2103#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Adresse2'            , 'Adr', 'Sonst') AS "F#2104#",
  DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa',   'Anrede', 'Adr', 'Sonst')), 1, 'Herrn',  2, 'Frau', 3, 'An die Eltern von', '') AS "F#10000245#",
  CASE WHEN INSTR(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Adr', 'Sonst')              , ',') > 0 THEN NULL ELSE DECODE(TO_NUMBER(GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede', 'Adr', 'Sonst')),               1, 'Herrn', 2, 'Frau', 3, 'An die Eltern von', '') END AS "F#10000247#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Anrede'              , 'Adr', 'Sonst') AS "F#2105#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdA', 'BmAdA', 'Code'                 )) AS "F#10001654#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdA', 'BmAdA', 'Farbe'     , 'FIRST')) AS "F#10001656#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdA', 'BmAdA', 'Abkuerzung'           )) AS "F#10001658#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdA', 'BmAdA', 'Txt'                  )) AS "F#10001660#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdA', 'BmAdA', 'ZusatzText'           )) AS "F#10001662#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdB', 'BmAdB', 'Code'                 )) AS "F#10001664#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdB', 'BmAdB', 'Farbe'     , 'FIRST')) AS "F#10001666#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdB', 'BmAdB', 'Abkuerzung'           )) AS "F#10001668#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdB', 'BmAdB', 'Txt'                  )) AS "F#10001670#",
  RTRIM(GetDfOfDfItemByAnbindung(Fa.FaId, 'Fa', 'Adr', 'Sonst', 'BmAdB', 'BmAdB', 'ZusatzText'           )) AS "F#10001672#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Bezeichnung'         , 'Adr', 'Sonst') AS "F#2106#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Code'                , 'Adr', 'Sonst') AS "F#860#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'eMail'               , 'Adr', 'Sonst') AS "F#2107#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'EAN'    , 'Adr', 'Sonst') AS "F#4663#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Adr', 'Sonst') AS "F#864#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Fax'                 , 'Adr', 'Sonst') AS "F#2108#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung'          , 'Adr', 'Sonst') AS "F#863#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Land'                , 'Adr', 'Sonst') AS "F#2110#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Name'                , 'Adr', 'Sonst') AS "F#2111#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Ort'                 , 'Adr', 'Sonst') AS "F#2112#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Badge'          , 'Adr', 'Sonst') AS "F#10000240#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Kurzel'          , 'Adr', 'Sonst') AS "F#10000241#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Pager'          , 'Adr', 'Sonst') AS "F#10000242#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'PEP_Tel_Intern'          , 'Adr', 'Sonst') AS "F#10000243#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Plz'                 , 'Adr', 'Sonst') AS "F#2113#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Reihenfolge'         , 'Adr', 'Sonst') AS "F#2114#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Code'         , 'Adr', 'Sonst') AS "F#10000217#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Abkuerzung'   , 'Adr', 'Sonst') AS "F#10000219#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Df_Spr_Txt'          , 'Adr', 'Sonst') AS "F#10000221#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon1'            , 'Adr', 'Sonst') AS "F#2115#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Telefon2'            , 'Adr', 'Sonst') AS "F#2116#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt'                 , 'Adr', 'Sonst') AS "F#861#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Titel'               , 'Adr', 'Sonst') AS "F#2117#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'Vorname'             , 'Adr', 'Sonst') AS "F#2118#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz1'         , 'Adr', 'Sonst') AS "F#10000227#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz2'         , 'Adr', 'Sonst') AS "F#10000229#",
  GetDfByAnbindung(Fa.FaId,'Fa','Zusatz3'         , 'Adr', 'Sonst') AS "F#10000231#",
  GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText'          , 'Adr', 'Sonst') AS "F#862#",
  Fa.NarkoseDatum AS "F#2882#",
  TO_CHAR(Fa.NarkoseZeit, 'HH24:MI') AS "F#2883#",
  Fa.OperationsDatum AS "F#1300#",
  TO_CHAR(Fa.OperationsZeit, 'HH24:MI') AS "F#1301#",
  Fa.VoreintrittsDatum AS "F#2880#",
  TO_CHAR(Fa.VoreintrittsZeit, 'HH24:MI') AS "F#2881#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Tc', 'Tc')) AS "F#770#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Tc', 'Tc') AS "F#774#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Tc', 'Tc')) AS "F#773#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Tc', 'Tc')) AS "F#771#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Tc', 'Tc')) AS "F#772#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Code', 'Ub', 'Ub')) AS "F#780#",
  GetPaColorByPaFA(Fa.PaId, Fa.FaId, 'Ub', 'Ub') AS "F#784#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Abkuerzung', 'Ub', 'Ub')) AS "F#783#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'Txt', 'Ub', 'Ub')) AS "F#781#",
  RTRIM(GetDfByAnbindung(Fa.FaId, 'Fa', 'ZusatzText', 'Ub', 'Ub')) AS "F#782#",
  TO_CHAR(Fa.Eintritt,'dd.mm.yy') || ' - ' || TO_CHAR(Fa.Austritt,'dd.mm.yy') AS "F#2063#",
  TO_CHAR(Fa.Eintritt,'dd.mm.yy') || ' ' || TO_CHAR(Fa.ZeitEintritt,'HH24:MI') || ' - ' || TO_CHAR(Fa.Austritt,'dd.mm.yy') || ' ' || TO_CHAR(Fa.ZeitAustritt,'HH24:MI') AS "F#2064#",
  GetZSABezeichnungAtDate (SYSDATE, Fa.FaId) AS "F#6217#",
  GetZSABisDatumAtDate (SYSDATE, Fa.FaId) AS "F#6216#",
  GetZSAVonDatumAtDate (SYSDATE, Fa.FaId) AS "F#6215#",
  Fa.Zimmernummer AS "F#484#",
  Fa.Zimmertelefon AS "F#485#",
  Fa.Zimmernummer AS "F#2169#",
  Fa.FaId AS "F#571#",
  LepInfo(Fa.FaId, (select DateItem From tmpDateList Where rownum=1)) AS "F#2226#",
  LepInfo(Fa.FaId, (select DateItem-2 From tmpDateList Where rownum=1)) AS "F#2228#",
  LepInfo(Fa.FaId, (select DateItem-1 From tmpDateList Where rownum=1)) AS "F#2227#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'BmPa3', 'BmPa3')) AS "F#832#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'BmPa4', 'BmPa4')) AS "F#842#",
  RTRIM(GetDfByPF(Pa.PaId, -1, 'ZusatzText', 'BmPa5', 'BmPa5')) AS "F#852#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'ZusatzText','BmAdA','BmAdA','Kntk2') AS "F#1142#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'ZusatzText','BmAdB','BmAdB','Kntk2') AS "F#1152#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'ZusatzText','BmAdA','BmAdA','Kntk3') AS "F#1162#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'ZusatzText','BmAdB','BmAdB','Kntk3') AS "F#1172#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'ZusatzText','BmAdA','BmAdA','Kntkt') AS "F#1122#",
  GetDfItemOfAdrByPF(Pa.PaId, -1,'ZusatzText','BmAdB','BmAdB','Kntkt') AS "F#1132#",
  Pa.Name || ' ' || Pa.Vorname || DECODE(NVL(LENGTH(Fa.FID), 0), 0, '', ' (FID ' || Fa.FID || ')') AS "F#2049#",
  Pa.Name || ' ' || Pa.Vorname || DECODE(NVL(LENGTH(Fa.Zimmernummer), 0), 0, '', ' , ' || Fa.Zimmernummer) AS "F#2051#",
  Pa.Name || ' ' || Pa.Vorname || DECODE(NVL(LENGTH(Fa.Zimmernummer), 0), 0, '', ' , ' || Fa.Zimmernummer) || DECODE(NVL(LENGTH(Fa.Zimmertelefon), 0), 0, '', ' ' || Fa.Zimmertelefon) AS "F#2052#"
FROM
 Pa, Fa, PaSuchfelder
 ,  zimmer,mitarbeiter,hierarchie,bel,pa,fa,akt,stammplus,knoten, Terminart, Rs,
  (SELECT
     DocADMIN.ELDAT_CUST_1235.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_1235, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_1235.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_1235.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_1235.Struktur_Element_Id = 1146 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_1235.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Fitnessraum,       -->  Angepasst an Livesystem                                                                                               
   (SELECT
     DocADMIN.ELDAT_CUST_751.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_751, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_751.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_751.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_751.Struktur_Element_Id = 858 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_751.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) Dispens_Somatik,    
   (SELECT
     DocADMIN.ELDAT_CUST_752.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_752, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_752.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_752.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_752.Struktur_Element_Id = 858 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_752.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) Dispens_Weitere,                  
  (SELECT
     DocADMIN.ELDAT_CUST_746.*,
     DocDBA.Dokument.FaId       
   FROM
     DocAdmin.ELDAT_CUST_746, DocDba.Dokument, DocDba.Dokument_Version                                
   WHERE
     ELDAT_CUST_746.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_746.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_746.Struktur_Element_Id = 857 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_746.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Ausgang,                                
  (SELECT
     DocADMIN.ELDAT_CUST_747.*,
     DocDBA.Dokument.FaId       
   FROM
     DocAdmin.ELDAT_CUST_747, DocDba.Dokument, DocDba.Dokument_Version                                
   WHERE
     ELDAT_CUST_747.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_747.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_747.Struktur_Element_Id = 857 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_747.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Urlaub,                                
  (SELECT
     DocADMIN.ELDAT_CUST_1214.*,
     DocDBA.Dokument.FaId       
   FROM
     DocAdmin.ELDAT_CUST_1214, DocDba.Dokument, DocDba.Dokument_Version                                
   WHERE
     ELDAT_CUST_1214.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_1214.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_1214.Struktur_Element_Id = 1139 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_1214.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Entzug,  --> Angepasst an LIVE                                                                                 
  (SELECT
     DocADMIN.ELDAT_CUST_1215.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_1215, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_1215.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_1215.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_1215.Struktur_Element_Id = 1139 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_1215.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Essensort,   -->  Angepasst an LIVE                              
  (SELECT
     DocADMIN.ELDAT_CUST_1140.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_1140, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_1140.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_1140.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_1140.Struktur_Element_Id = 1112 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_1140.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Startseite_Pflegedok,  -->  Angepasst (FF - STV)                                                                                            
  (SELECT
     DocADMIN.ELDAT_CUST_236.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_236, DocDba.Dokument, DocDba.Dokument_Version, DocDba.Struktur_element       
   WHERE
     ELDAT_CUST_236.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_236.Version_Id = Dokument_Version.Version_Id AND
     Struktur_element.register_guid = (SELECT register_guid
                            FROM struktur_element
                           WHERE struktur_element_id =230) AND
     ELDAT_CUST_236.Struktur_Element_Id =Struktur_element.struktur_element_id AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_236.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEID230,  
  (SELECT
     DocADMIN.ELDAT_CUST_1152.*,
     DocDBA.Dokument.FaId
   FROM
     DocAdmin.ELDAT_CUST_1152, DocDba.Dokument, DocDba.Dokument_Version
   WHERE
     ELDAT_CUST_1152.Dokument_Id = Dokument_Version.Dokument_Id AND
     ELDAT_CUST_1152.Version_Id = Dokument_Version.Version_Id AND
     ELDAT_CUST_1152.Struktur_Element_Id = 1115 AND
     Dokument.Dokument_Id = Dokument_Version.Dokument_Id AND
     Dokument_Version.Dokument_Id = Dokument.Dokument_Id AND
     Dokument_Version.Dokument_Id = ELDAT_CUST_1152.Dokument_Id AND
     Dokument_Version.Ist_Aktuell = 'T'
     ) SEId_Aus_Uebertritt    -->  Angepasst an LIVE                                                                                       
WHERE
     Fa.PaId  = Pa.PaId
 AND PaSuchfelder.PaId = Pa.PaId
 AND Fa.Eintritt <= :dteRight
 AND Fa.AbschlussDatum >= :dteLeft
 AND Pa.PaId=DECODE(to_number(:PaId), -1, Pa.PaId, to_number(:PaId))
 AND Fa.PaId=DECODE(to_number(:PaId), -1, Fa.PaId, to_number(:PaId))
 AND Fa.FaId=DECODE(to_number(:FaId), -1, Fa.FaId, to_number(:FaId))
  AND (
 SEId_Fitnessraum.FaId (+) = Fa.FaId AND
 Dispens_Somatik.FaId (+) = Fa.FaId AND     
 Dispens_Weitere.FaId (+) = Fa.FaId AND     
 SEId_Ausgang.FaId (+) = Fa.FaId AND
 SEId_Urlaub.FaId (+) = Fa.FaId AND       
 SEId_Entzug.FaId (+) = Fa.FaId AND
 SEId_Essensort.FaId (+) = Fa.FaId AND
 SEId_Aus_Uebertritt.FaId (+) = Fa.FaId AND
 SEId_Startseite_Pflegedok.FaId (+) = Fa.FaId AND     
   zimmer.id = mitarbeiter.zimmer_id
   AND Knoten.Id  = Mitarbeiter.Id
   AND Rs.RsId = Mitarbeiter.Id
   AND hierarchie.knoten_id = zimmer.gruppen_id_pep
   AND bel.rsid (+) = mitarbeiter.id
   AND DECODE(bel.belcode (+), 'DA', 'T', 'DS', 'T', 'DSI', 'T', 'DB', 'T', 'F') = 'T'
   AND trunc(bel.beginn (+)) <= :dteRight
   AND bel.ende (+) > :dteLeft
   AND pa.paid (+) = bel.paid
   AND fa.faid (+) = bel.faid
   AND fa.PaId (+) = bel.PaId
   AND akt.aktid (+) = bel.aktid
   AND SEId230.FaId (+) =Fa.FaId      
   AND terminart.taid(+) = akt.taid
   AND stammplus.mitarbeiter_id = mitarbeiter.id
   AND stammplus.gueltig_ab <= :dteRight
   AND stammplus.gueltig_bis >= :dteLeft
   AND ((Mitarbeiter.Reserve = 'F'))
)