SELECT
  patient_view.id AS patient,
  patient_view.cis_pid AS pid,
  CASE WHEN patient_view.gender='Male' THEN 'Herr' ELSE 'Frau' END || ' ' || COALESCE(patient_view.last_name, '') || ' ' || COALESCE(patient_view.first_name, '') AS patient_name,
  patient_view.four_letter_code,
    
  ((cast(response AS json))->>'Datum') as datum,
  TO_DATE(((cast(response AS json))->>'Datum'), 'YYYY-MM-DD HH24:MI:SS')  as datum_date,
  SUBSTRING(((cast(response AS json))->>'Datum'),12,5) AS datum_time,
  SUBSTRING(((cast(response AS json))->>'Datum'),1,4)::integer AS datum_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'Datum'), 'YYYY-MM-DD HH24:MI:SS')) AS datum_week,
  ((cast(response AS json))->>'EWHOQOL1') as ewhoqol1,
  ((cast(response AS json))->>'EWHOQOL1014_EWHOQOL10') as ewhoqol1014_ewhoqol10,
  ((cast(response AS json))->>'EWHOQOL1014_EWHOQOL11') as ewhoqol1014_ewhoqol11,
  ((cast(response AS json))->>'EWHOQOL15') as ewhoqol15,
  ((cast(response AS json))->>'EWHOQOL1625_EWHOQOL16') as ewhoqol1625_ewhoqol16,
  ((cast(response AS json))->>'EWHOQOL1625_EWHOQOL17') as ewhoqol1625_ewhoqol17,
  ((cast(response AS json))->>'EWHOQOL1625_EWHOQOL18') as ewhoqol1625_ewhoqol18,
  ((cast(response AS json))->>'EWHOQOL1625_EWHOQOL19') as ewhoqol1625_ewhoqol19,
  ((cast(response AS json))->>'EWHOQOL2') as ewhoqol2,
  ((cast(response AS json))->>'EWHOQOL26') as ewhoqol26,
  ((cast(response AS json))->>'EWHOQOL39_EWHOQOL3') as ewhoqol39_ewhoqol3,
  ((cast(response AS json))->>'EWHOQOL39_EWHOQOL4') as ewhoqol39_ewhoqol4,
  ((cast(response AS json))->>'EWHOQOL39_EWHOQOL5') as ewhoqol39_ewhoqol5,
  ((cast(response AS json))->>'EWHOQOL39_EWHOQOL6') as ewhoqol39_ewhoqol6,
  ((cast(response AS json))->>'EWHOQOL39_EWHOQOL7') as ewhoqol39_ewhoqol7,
  ((cast(response AS json))->>'Erhebungszeitpunkt') as erhebungszeitpunkt,
  ((cast(response AS json))->>'FID') as fid,
  ((cast(response AS json))->>'PID') as pid,
  ((cast(response AS json))->>'andererZeitpunkt') as andererzeitpunkt,
  ((cast(response AS json))->>'datestamp') as datestamp,
  TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')  as datestamp_date,
  SUBSTRING(((cast(response AS json))->>'datestamp'),12,5) AS datestamp_time,
  SUBSTRING(((cast(response AS json))->>'datestamp'),1,4)::integer AS datestamp_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')) AS datestamp_week,
  ((cast(response AS json))->>'id') as id,
  ((cast(response AS json))->>'lastpage') as lastpage,
  ((cast(response AS json))->>'optinomixHASH') as optinomixhash,
  ((cast(response AS json))->>'startdate') as startdate,
  TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')  as startdate_date,
  SUBSTRING(((cast(response AS json))->>'startdate'),12,5) AS startdate_time,
  SUBSTRING(((cast(response AS json))->>'startdate'),1,4)::integer AS startdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')) AS startdate_week,
  ((cast(response AS json))->>'startlanguage') as startlanguage,
  ((cast(response AS json))->>'submitdate') as submitdate,
  TO_DATE(((cast(response AS json))->>'submitdate'), 'YYYY-MM-DD HH24:MI:SS')  as submitdate_date,
  SUBSTRING(((cast(response AS json))->>'submitdate'),12,5) AS submitdate_time,
  SUBSTRING(((cast(response AS json))->>'submitdate'),1,4)::integer AS submitdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'submitdate'), 'YYYY-MM-DD HH24:MI:SS')) AS submitdate_week,
  random_hash,
  scheduled,
  filled,
  module,
  survey_response.id AS survey_response_id,  
  stay.cis_fid AS fid,  
  stay.id AS stay,  
  stay.first_contact AS first_contact,  
  stay.start AS start,  
  to_char(stay.start, 'YYYY') AS start_year,
  to_char(stay.start, 'WW') AS start_week,
  to_char(stay.start, 'HH24:MI') AS start_time,
  stay.stop AS stop,  
  stay.stop_status AS stop_status,  
  stay.lead_therapist AS lead_therapist,  
  stay.deputy_lead_therapist AS deputy_lead_therapist,  
  stay.cis_lead_doctor AS lead_doctor,  
  stay.insurance_number AS insurance_number  

FROM survey_response 
LEFT JOIN patient_view ON(survey_response.patient = patient_view.id) 
LEFT JOIN stay ON(patient_view.stay_id = stay.id) 

WHERE module = 'com.optinomic.apps.whoqol'
AND patient_view.id=1
AND to_char(stay.start, 'YYYY') = '2014'

