SELECT
  patient.id AS pid,
  patient,
  CASE WHEN patient.gender='Male' THEN 'Herr' ELSE 'Frau' END || ' ' || COALESCE(patient.last_name, '') || ' ' || COALESCE(patient.first_name, '') AS patient_name,
  patient.four_letter_code,
    
  ((cast(response AS json))->>'Datum') as datum,
  TO_DATE(((cast(response AS json))->>'Datum'), 'YYYY-MM-DD HH24:MI:SS')  as datum_date,
  SUBSTRING(((cast(response AS json))->>'Datum'),12,5) AS datum_time,
  SUBSTRING(((cast(response AS json))->>'Datum'),1,4)::integer AS datum_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'Datum'), 'YYYY-MM-DD HH24:MI:SS')) AS datum_week,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB1')::integer as escibelastung_escib1,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB2')::integer as escibelastung_escib2,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB3')::integer as escibelastung_escib3,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB4')::integer as escibelastung_escib4,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB5')::integer as escibelastung_escib5,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB6')::integer as escibelastung_escib6,
  ((cast(response AS json))->>'ESCIBelastung_ESCIB7')::integer as escibelastung_escib7,
  ((cast(response AS json))->>'ESCICoping_ESCIC1')::integer as escicoping_escic01,
  ((cast(response AS json))->>'ESCICoping_ESCIC2')::integer as escicoping_escic02,
  ((cast(response AS json))->>'ESCICoping_ESCIC3')::integer as escicoping_escic03,
  ((cast(response AS json))->>'ESCICoping_ESCIC4')::integer as escicoping_escic04,
  ((cast(response AS json))->>'ESCICoping_ESCIC5')::integer as escicoping_escic05,
  ((cast(response AS json))->>'ESCICoping_ESCIC6')::integer as escicoping_escic06,
  ((cast(response AS json))->>'ESCICoping_ESCIC7')::integer as escicoping_escic07,
  ((cast(response AS json))->>'ESCICoping_ESCIC8')::integer as escicoping_escic08,
  ((cast(response AS json))->>'ESCICoping_ESCIC90')::integer as escicoping_escic09,
  ((cast(response AS json))->>'ESCICoping_ESCIC10')::integer as escicoping_escic10,
  ((cast(response AS json))->>'ESCICoping_ESCIC11')::integer as escicoping_escic11,
  ((cast(response AS json))->>'ESCICoping_ESCIC12')::integer as escicoping_escic12,
  ((cast(response AS json))->>'ESCICoping_ESCIC13')::integer as escicoping_escic13,
  ((cast(response AS json))->>'ESCICoping_ESCIC14')::integer as escicoping_escic14,
  ((cast(response AS json))->>'ESCICoping_ESCIC15')::integer as escicoping_escic15,
  ((cast(response AS json))->>'ESCICoping_ESCIC16')::integer as escicoping_escic16,
  ((cast(response AS json))->>'ESCICoping_ESCIC17')::integer as escicoping_escic17,
  ((cast(response AS json))->>'ESCICoping_ESCIC18')::integer as escicoping_escic18,
  ((cast(response AS json))->>'ESCICoping_ESCIC19')::integer as escicoping_escic19,
  ((cast(response AS json))->>'ESCICoping_ESCIC20')::integer as escicoping_escic20,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO1')::integer as escioverstaining_escio1,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO2')::integer as escioverstaining_escio2,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO3')::integer as escioverstaining_escio3,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO4')::integer as escioverstaining_escio4,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO5')::integer as escioverstaining_escio5,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO6')::integer as escioverstaining_escio6,
  ((cast(response AS json))->>'ESCIOverstaining_ESCIO7')::integer as escioverstaining_escio7,
  ((cast(response AS json))->>'ESCISymptome_ESCI10')::integer as escisymptome_esci10,
  ((cast(response AS json))->>'ESCISymptome_ESCI11')::integer as escisymptome_esci11,
  ((cast(response AS json))->>'ESCISymptome_ESCI12')::integer as escisymptome_esci12,
  ((cast(response AS json))->>'ESCISymptome_ESCI13')::integer as escisymptome_esci13,
  ((cast(response AS json))->>'ESCISymptome_ESCIS1')::integer as escisymptome_escis1,
  ((cast(response AS json))->>'ESCISymptome_ESCIS2')::integer as escisymptome_escis2,
  ((cast(response AS json))->>'ESCISymptome_ESCIS3')::integer as escisymptome_escis3,
  ((cast(response AS json))->>'ESCISymptome_ESCIS4')::integer as escisymptome_escis4,
  ((cast(response AS json))->>'ESCISymptome_ESCIS5')::integer as escisymptome_escis5,
  ((cast(response AS json))->>'ESCISymptome_ESCIS6')::integer as escisymptome_escis6,
  ((cast(response AS json))->>'ESCISymptome_ESCIS7')::integer as escisymptome_escis7,
  ((cast(response AS json))->>'ESCISymptome_ESCIS8')::integer as escisymptome_escis8,
  ((cast(response AS json))->>'ESCISymptome_ESCIS9')::integer as escisymptome_escis9,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU1')::integer as esciunsicherheit_esciu1,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU2')::integer as esciunsicherheit_esciu2,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU3')::integer as esciunsicherheit_esciu3,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU4')::integer as esciunsicherheit_esciu4,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU5')::integer as esciunsicherheit_esciu5,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU6')::integer as esciunsicherheit_esciu6,
  ((cast(response AS json))->>'ESCIUnsicherheit_ESCIU7')::integer as esciunsicherheit_esciu7,
  ((cast(response AS json))->>'Erhebungszeitpunkt') as erhebungszeitpunkt,
  ((cast(response AS json))->>'FID') as fid,
  ((cast(response AS json))->>'PID') as pid,
  ((cast(response AS json))->>'andererZeitpunkt') as andererzeitpunkt,
  ((cast(response AS json))->>'datestamp') as datestamp,
  TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')  as datestamp_date,
  SUBSTRING(((cast(response AS json))->>'datestamp'),12,5) AS datestamp_time,
  SUBSTRING(((cast(response AS json))->>'datestamp'),1,4)::integer AS datestamp_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'datestamp'), 'YYYY-MM-DD HH24:MI:SS')) AS datestamp_week,
  ((cast(response AS json))->>'id') as id,
  ((cast(response AS json))->>'lastpage') as lastpage,
  ((cast(response AS json))->>'optinomixHASH') as optinomixhash,
  ((cast(response AS json))->>'startdate') as startdate,
  TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')  as startdate_date,
  SUBSTRING(((cast(response AS json))->>'startdate'),12,5) AS startdate_time,
  SUBSTRING(((cast(response AS json))->>'startdate'),1,4)::integer AS startdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'startdate'), 'YYYY-MM-DD HH24:MI:SS')) AS startdate_week,
  ((cast(response AS json))->>'startlanguage') as startlanguage,
  ((cast(response AS json))->>'submitdate') as submitdate,
  TO_DATE(((cast(response AS json))->>'submitdate'), 'YYYY-MM-DD HH24:MI:SS')  as submitdate_date,
  SUBSTRING(((cast(response AS json))->>'submitdate'),12,5) AS submitdate_time,
  SUBSTRING(((cast(response AS json))->>'submitdate'),1,4)::integer AS submitdate_year,
  EXTRACT(WEEK FROM TO_DATE(((cast(response AS json))->>'submitdate'), 'YYYY-MM-DD HH24:MI:SS')) AS submitdate_week,

  random_hash,
  scheduled,
  filled,
  module,
  survey_response.id AS survey_response_id  

FROM survey_response 
INNER JOIN patient ON(survey_response.patient = patient.id) 

WHERE module = 'ch.suedhang.apps.sci';
